### ISSUE TITLE
R22 saturation enthalpy close to critical point

### ISSUE THREAD

**Issue by thorade** [usnistgov/REFPROP-wrappers#152]
Hi,
I am running RefProp 10.0 on Windows 10 64bit, calling the DLL from Modelica using a wrapper developed by Modelon.
When I just sweep p and T for R22 and calculate the saturation enthalpy from p, I get the following plot:
<img width="292" alt="ph_sat_consistency_ModelonMedia" src="https://user-images.githubusercontent.com/314571/55107942-c598f200-50d2-11e9-8abc-33212ce6754f.png">
Close to the critical point, dew and bubble enthalpy do not reach the same value. But when calculating the saturation tables from the RefProp GUI, the values do match. 
So, currently I assume it is an issue in the wapper I am using, but any hints how to fix it would be appreciated. Do the saturation tables call the functions in a special way?
Thanks,
Matthis

**Comment by EricLemmon** [comment]
Hi Matthis,

I've transferred your request from the Refprop-issues repository to the Refprop-wrappers repository where all issues concerning linking with the DLL or the Fortran code should be.

I do not understand why you have two lines in your plot above the critical pressure.  There is only one state there for any given P and T, and thus it should be a single line.

Eric

**Comment by thorade** [comment]
Probably my description was not good, I do several plots, but for this plot it is really just h_bub(p) and h_dew(p). Both are implemented to return the critical enthalpy for supercritical pressures, but it seems they are not able to really reach the critical point, and I was mostly wondering whether this is due to my wrapper, or to the RefProp part. Other fluids with same wrapper do not show this gap, and same fluid with RefProp GUI also does not show this gap.

**Comment by EricLemmon** [comment]
I believe this is due to your wrapper.  I looked at the equation of state for R22 and its ability to calculate consistent properties in the critical region and it works remarkably well.  Below is a picture of it.  The red line is the saturation line and the blue line is the critical isotherm.  That isotherm shows absolutely no negative slope anywhere and the curvature is always negative below the critical density and positive above it.  So there can be no false upper or lower roots very close to the critical point, as happens with many equations of state.

![image](https://user-images.githubusercontent.com/42392984/55174890-e64d6000-5143-11e9-9e68-a88696576176.png)

**Comment by thorade** [comment]
Thanks for checking that, I will close this issue, and report if I have new insights.
Just a minor question: It looks like the two red lines do not meet, but I assume this is just the plot!?

**Comment by EricLemmon** [comment]
Actually it's just the blue line on top of the red line.  I used the Calculate/Phase Boundary option in the GUI to calculate the points plotted in that graph.  The inputs to this option are a density range instead of a temperature or pressure range, from which you can obtain a very smooth set of points in the critical region, assuming that the equation of state behaves very well in that region.  

This is particularly helpful with mixtures since you don't have to worry about whether to calculate bubble or dew point in the retrograde region as either a function of temperature or pressure in order to obtain all points needed to plot the graph.  The output simply passes through all states from low densities in the vapor to high densities in the liquid, and these can then be used to make very smooth graphs.  

This option uses the SATGV routine developed in version 9.1 that is very well suited to either density or entropy inputs along the saturation line.  The letters "GV" in this subroutine are used in honor of our good friend and colleague from India who we just call GV because his full name is not pronounceable by simple native English speakers like myself.  He is one of the authors of the now famous PIP, a "property" that we use to evaluate all of our new equations of state because it is extremely sensitive in the critical region to small flaws and really expands any bad behavior that would otherwise not be noticeable on other graphs.  He is also the one that gave a lot of help during the development of the SATGV routine through his entropy marching concepts that we later turned into the density marching algorithm now in use in versions 9.1 and 10.0.

**Comment by thorade** [comment]
Thanks, I appreciate that additional information!
We saw this error when generating tables, that are later to be used for SBTL, I think we should update the data generation algorithm to also density as input (and convert to a grid that is equidistant in h in a second step).
I read the paper by GV about PIP some years ago and enjoyed it. In dynamic simulations, the saturation routines will sometimes be called with supercritical input, and returning the PIP-switching point is one possible approach in that case.

**Comment by ianhbell** [comment]
There are also some alternative extrapolation approaches that might be vaguely suitable for extrapolation in the middle of a dynamic simulation to allow you to relax back to a subcritical state when you reach the final solution.  One or two come to mind, but to be honest I think it comes down to try it and see.  Thing like negative latent heats I could imagine being a problem.  If all you care about is the vapor pressure, then you’ve got some options.

**Comment by thorade** [comment]
Note: R22 saturation close to critical point also discussed here:
https://github.com/usnistgov/REFPROP-issues/issues/406
