### ISSUE TITLE
Default mixture type in excel wrapper?

### ISSUE THREAD

**Issue by jeffkshaw** [usnistgov/REFPROP-wrappers#156]
### Description

What is the default mixture type in the excel wrapper, mole or mass, when using the syntax below?

### Steps to Reproduce

```
=refprop("D","Ethylene Glycol;Water|0.5;0.5","TP","SI",273.15,0.1,0)
```

**Expected behavior:** Mole fraction.

**Actual behavior:** Unknown

### Versions

**REFPROP Version:** 10
**Operating System and Version:** Windows
**Access Method:** Excel wrapper

### Additional Information

I haven't found this listed on the mixtures tab of refprop.xla.  Perhaps I missed this in the documentation and my apologies if so.

**Comment by EricLemmon** [comment]
I've moved your issue to the Refprop-wrappers repository since it deals with Excel, but this resulted in the most amazing thing ever happening.  Both repositories have used exactly 155 entries, and yours was the 156th in the Refprop/issues repository, and is now ironically the 156th issue in this wrappers repository!  I apologize that there is no prize for such an accomplishment.

Refprop uses mole fractions as the default for all calculations.  Mass based calculations require additional options to specify the use of these units.  For your example, a 50/50 mass fraction mixture would be entered as:
```
=refprop("D","Ethylene Glycol;Water|0.5;0.5 mass","TP","SI",273.15,0.1,0)
```

If you have not had a chance to look at the Refprop.xls workbook, take a quick browse through it, there are many examples showing how nearly all of the features work.  In fact, there are probably far more examples than you need, and thus your prize is sorting through them all.

If this answers your questions, would you close this issue?

**Comment by jeffkshaw** [comment]
You are a gentleman and a scholar.  I must have missed this in the refprop.xls, I downloaded the raw version on github.  Thank you for your time.  You are a gentleman and a scholar, and the work you do is noble, valued, and important.

**Comment by EricLemmon** [comment]
Thanks for your wonderful comments!  I need them on a day like today.
