### ISSUE TITLE
Incorrect Values for Methane:Ethane Mixture 

### ISSUE THREAD

**Issue by Liamgallagher678** [usnistgov/REFPROP-wrappers#165]
### Description

I wish to calculate the Enthalpy of a mixture at it's bubble point. The mixture is an LNG Methane;Ethane components with composition of [0.965,0.035] on a Molar Basis. When using REFPROP GUI I receive a different enthalpy to the value I try generate on Matlab. 

### Steps to Reproduce
Mix = 'Methane;Ethane'

Hlr = RP.REFPROPdll(Mix,'TQ','HLIQ',int8(0),int8(0),int8(0),117.32,0,[0.965,0.035]);
Hlrr = double(Hlr.Output);
Hl = Hlrr(1); % Print the Enthalpy of the Liquid Phase

**Actual Behaviour**

Hl = 151.4675 J/mol

**Expected Behaviour:**
Hl = 291.457 J/mol

### Versions

**REFPROP Version: 10** [REFPROP version you are using]  
**Operating System and Version: Windows**
**Access Method: Matlab Wrapper** 

### Additional Information

If possible, please post examples and/or screenshots of the issue.

**Comment by EricLemmon** [comment]
Take a look at this and see if it answers your questions:

https://pages.nist.gov/REFPROP-docs/#reference-states-enthalpy-and-entropy-differences

This page does not explain how to set the flag for mixtures (with a call to REFPROPdll) to set the reference state to "Currently Defined Mixture" (as shown in the GUI), so I'll explain it here.  When calling from Fortran, the syntax would be:

      call REFPROP (' ','FLAGS','SETREF',0,0,2,0d0,0d0,z,Ou,hfle,iUnitx,x,y,x3,q,ierr,herr) 

I believe that the call would look like this in your example:
= RP.REFPROPdll(' ','FLAGS','SETREF',int8(0),int8(0),int8(2),0,0,0);

Please verify this here in your comments so that others can learn as well.

**Comment by Liamgallagher678** [comment]
Hi Eric, thank you for the timely response.
I used the legacy API to set the reference state enthalpy to the correct value.
i used the following code

B = RP.SETREFdll('OTH',int8(2),X,295.47 , 2.559, 117.32, 152);
A = RP.ABFLSHdll('TP', 117.32, 152, [0.965,0.035],int8(030));

where A was a subroutine i used to verify the correct values where being output by Matlab. 

Thank-you for the help.

**Comment by Liamgallagher678** [comment]
This is the line of code I used to set the reference state to the desired properties
X = [0.965,0.035]
C = RP.SETFLUIDSdll('Methane*Ethane');
B = RP.REFPROPdll('','SETREF','OTH;295.47;2.559;117.32;152',int8(0),int8(0),int8(2),117.32,152,X);

where X was the composition.

**Comment by EricLemmon** [comment]
Thanks for reporting the lines you used, that will indeed help others to understand how this works.

I don't think you need to send the 117.32 and 152 values at the end of the line, everything it needs to set this up is contained in the other inputs.  Those last two values are most likely just ignored.
