### ISSUE TITLE
Metal Materials' Thermal Properties

### ISSUE THREAD

**Issue by Yili-Zhang** [usnistgov/REFPROP-wrappers#177]
Hi,

I am recently simulating a heat exchanger's working process with the heat exchanger made of metal 'Inconel 718'. Basically I need to constantly update the material's thermal conductivity, and here is the code I tried in MatLAB:

``` python
M='Inconel_718';

K=RP.REFPROPdll(M,'T','TCX',MASS_SI,int8(0),int8(0),T_interm,NaN,{1.0});
K_num=double(K.Output);
k_t=K_num(1);
```
Since the 'Inconel_718' works in EES, so I copied the same form over here, but it seems not working at all. Here is the outcome:

``` python
k_t =

    -9999990
```
In the mean time, I tried other properties with the metal material, such as enthalpy, temperature, etc., the results were the same. Therefore, I believe 'Inconel_718' is not the correct way to reprent the metal material type. I wonder if you would know the correct way? If there is no predefined material 'Inconel 718' in refprop, may I create my own? If I may, how could I do it?

Plus, I know the thermal conductivity function has some problems as well, I will pose another issue on that.

Thanks,

-Yili

**Comment by ianhbell** [comment]
REFPROP does not support solid properties (REFPROP is for fluid properties, basically), and this is not within the scope of REFPROP, and therefore this will likely never be supported.  For this, your best bet is EES, or writing your own empirical curve fits, since you should be able to find tabulated values of thermal conductivity for this alloy.
