### ISSUE TITLE
REFPROP10 with my Matlab2011b

### ISSUE THREAD

**Issue by JacksonBrazMarcinichen** [usnistgov/REFPROP-wrappers#217]
### Additional Information

If possible, please post examples and/or screenshots of the issue.

Hello Ian

Following Eric's advise, I'm sending below my issue

I’m trying to run the REFPROP10 via matlab since I need the properties of R1336mzzz and my previous REFPROP, which is running smoothly with MATLAB, does not have such fluid.

The code is not running and the file refpropm.m is returning zero in the function below:

``` matlab

    % the following returns 0 if refprop.dll does not exist, 1 if refprop.dll is a variable name in the workspace, 2 if C:\Program Files (x86)\REFPROP\refprop.dll exist, and 3 if refprop.dll exist but is a .dll file in the MATLAB path
    if ~ismember(exist(strcat(BasePath, dllName),'file'),[2 3])
        dllName = lower(dllName);
```

I would appreciate your support/help. Maybe some dll is not correctly updated in  my REFPROP10 folder (refprop.dll or refprp64.dll or rp_proto64.m or refpropm.m

Thanks in advance and wish you a lovely day

Jackson

**Comment by ianhbell** [comment]
Please fill out the entire template next time so that we have the information that we need to better help you.

The ``refpropm.m`` interface is no longer supported, rather the Python interface in MATLAB is the only thing that we actively support.  That said, the legacy matlab interface should still work.  Please see this comment about the rp_proto: https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/MATLAB/legacy#potential-problems .  I don't think you need the thunk file anymore...

**Comment by JacksonBrazMarcinichen** [comment]
Dear Ian,

 

Sorry if it was not so clear but I’m from the old school, i.e., simple questions simple answers and problem is solved.(no stress and never a lot of days for solutions, life is simple)

 

Your link was not useful for my understanding and I’ll put my new generation engineer to try to understand what is happening. Hope HE can find the solution for this new 21st century mess that was created not by us :)

 

Cheers and soon he will contact you if NO more 21st century doubts and issues happen

 

Jackson

 


  <https://docs.google.com/uc?export=download&id=1uN13e_OgSvcM8FkEyjoxEQC7X3eXE0ag&revid=0B5fUFjBpG3wYREdnMThMK2p2ZFVZWUxxbWM2cWVMcUdmaUpjPQ> 

Jackson Braz Marcinichen

CEO

EPFL Innovation Park, Bâtiment A

CH-1015 Lausanne, Switzerland

Tel : +41 78 976 0018 | www.jjcooling.com <http://www.jjcooling.com/>

**Comment by JacksonBrazMarcinichen** [comment]
Dear Ian,

 

See message below when trying to use REFPROP10 in Matlab2011b after follow all your instructions

 

*************************************

refpropm('T','P',101.325,'Q',0,'Water')

Error using loadlibrary (line 421)

Too many input arguments.

Error in ==>@()rp_proto64(BasePath) at 201

There was an error running C:\Program Files (x86)\REFPROP10\refpropm.m.

Run @()rp_proto64(BasePath) from the command line to reproduce the error and fix it.

 

 

Error in refpropm (line 217)

    [notfound,warnings]=loadlibrary(strcat(BasePath,dllName),prototype,'alias',libName);

 

Caused by:

    Error using rp_proto64

    Too many input arguments.

*************************************

 

 

Any help is welcome

 

Wish you a lovely day

 

Jackson

 


  <https://docs.google.com/uc?export=download&id=1uN13e_OgSvcM8FkEyjoxEQC7X3eXE0ag&revid=0B5fUFjBpG3wYREdnMThMK2p2ZFVZWUxxbWM2cWVMcUdmaUpjPQ> 

Jackson Braz Marcinichen

CEO

EPFL Innovation Park, Bâtiment A

CH-1015 Lausanne, Switzerland

Tel : +41 78 976 0018 | www.jjcooling.com <http://www.jjcooling.com/>

**Comment by ianhbell** [comment]
Can you please detail what "all your instructions" means?  Your MATLAB is pretty old, but that shouldn't pose a problem since I think this file has worked for quite some time.  

Are you running your script from ``c:\Program Files (x86)\REFPROP10``?  or somewhere else? Did you add the REFPROP folder to the Matlab path?

I would recommend to search your computer for any hidden rp_proto64 files and delete all of them, and then regenerate the rp_proto64 file once more.  Did you heed this device about what to do when not having installed REFPROP in a default location: https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/MATLAB/legacy#potential-problems ?
