### ISSUE TITLE
Can't do basic REFPROP-Matlab calls with legacy wrapper

### ISSUE THREAD

**Issue by HarrisonSkye** [usnistgov/REFPROP-wrappers#248]
### Description

I am trying to use the legacy Matlab wrapper with REFPROP v. 10 but keep getting errors doing basic function calls.  I am using the legacy Matlab wrapper, rather than the newer Python wrapper, since I have a complicated code that uses the legacy functions, and I don't yet want to up-convert my Matlab code. I'm using Matlab v.R2019b.

### Steps to Reproduce
When I use this code in Matlab:

> refpropm('T','P',101.325,'Q',0,'WATER')

**Expected behavior:** Based on https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/MATLAB/legacy

> ans =

> 373.1243

**Actual behavior:**
I get this error output in Matlab:

> Error using calllib
> Method was not found.
> 
> Error in refpropm (line 259)
>         [nc path hmix href ierr errTxt] = calllib(libName,'SETUPdll',numComponents,path,hmix,href,0,32*ones(255,1),10000,255,3,255);

### Versions

**REFPROP Version:** [10.0]  
**Operating System and Version:** [Windows 10]  
**Access Method:** [Matlab R2019b]  

### Additional Information

[Matlab-REFPROP error.pdf](https://github.com/usnistgov/REFPROP-wrappers/files/4221286/Matlab-REFPROP.error.pdf)

**Comment by ianhbell** [comment]
I'd recommend instead that you write a shim function that calls the Python interface that you could still call refpropm and would have the same interface. The legacy solution is riddled with pitfalls, which is why we no longer actively support it.

**Comment by HarrisonSkye** [comment]
Thanks for the response.  Do you have an example of a shim function you could share?  The shim function would be written in Matlab, right?  Can the shim function be written to accommodate different types of function calls?  I'm trying to do different types of function calls, such as:

Tco=refpropm('T','P',Pco,'Q',0,'CO2')
Pc = refpropm('P','T',Tc+273.15,'Q',1,'CO2'
PPH(1)=refpropm('H','T',Tdis+273.15,'P',Pc,'CO2')/1000;

Sorry if these are basic questions, but I'm not an advanced programmer.

**Comment by ianhbell** [comment]
A synonym for "shim" function would be interface function, but your function could be something like this in pseudocode:

``` python
def refpropm(output, in1, val1, in2, val2, fluid):
    if in1=='P' and in2 == 'Q':
        r = RP.REFPROPdll(fluid, 'PQ', output, RP.MASS_BASE_SI, 0, 0, val1, val2, [1.0])
        if r.ierr == 0:
            return r.Output[0]
    elif in1 == 'T' and in2 == 'Q':
...
```

**Comment by HarrisonSkye** [comment]
Thanks very much!  I'll give this a try.

**Comment by nathan-kamphuis** [comment]
Hi Ian,

Thanks for the advice. Harrison and I have legacy code using the refpropm.m function. I'm going to start working on a wrapper. I have a couple of quick questions about how the new call works:
1) aside from syntax is there a notable functionality difference between refpropm and RP.REFPROPdll that effects the way it is called? I.E., what I mean is are there property pairs or orderings that work for refpropm that do not for RP.REFPROPdll or viceversa?

Nate

**Comment by ianhbell** [comment]
Nope, the functionality in the legacy refpropm should be a subset of what is available in REFPROP 10.

**Comment by nathan-kamphuis** [comment]
Thanks Ian,

I noticed the set units of refpropm.m do not match any of the predefined iunit options in the documentation for v10. Can you give me a kick in the right direction in the documentation as to how to set a user defined set of units? The root issue is that the v10 documentation does not seem to support the default units for refpropm. Secondly, the listed units in iunits in the documentation under the REFPROPdll function call does not list all the physical properties that can be inputs or outputs. I assume that as a high level user using the python api for matlab we don't have access to the REFPROP function to define a custom unit list to match refpropm.m units.

Thanks for your advice and assistance.

Nate

**Comment by nathan-kamphuis** [comment]
Ian,

Also, why does this call fail: (MASS_SI is set using getenumdll with 'MASS BASE SI'
r = RP.REFPROPdll('Water','PQ','Q',MASS_SI,iMass,iFlag,101325,0.0,z);

r.ierr code 812

Yet these two calls work fine:
r = RP.REFPROPdll('Water','PQ','T',MASS_SI,iMass,iFlag,101325,0.0,z);
r = RP.REFPROPdll('Water','PQ','P',MASS_SI,iMass,iFlag,101325,0.0,z);

The full code is:
MASS_SI = RP.GETENUMdll(int8(0),'MASS BASE SI').iEnum;
iMass = int8(1); % 0: molar fractions; 1: mass fractions
iFlag = int8(0); % 0: don't call SATSPLN; 1: call SATSPLN
z = {1.0};
r = RP.REFPROPdll('Water','PQ','Q',MASS_SI,iMass,iFlag,101325,0.0,z);

error = int64(r.ierr);
output = double(r.Output);
T = output(1);
Temp_Units = string(r.hUnits);
Temp_Units = Temp_Units{1};

**Comment by ianhbell** [comment]
One note: you can do ``RP.MASS_BASE_SI`` which automatically extracts the enumerated value in the most modern version.

**Comment by ianhbell** [comment]
Also recommend to read the value of herr string if ierr > 0.
``` python
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
root = 'd:/Program Files (x86)/REFPROP'
RP = REFPROPFunctionLibrary(root)
RP.SETPATHdll(root)
r = RP.REFPROPdll('Water','PQ','Q',RP.MASS_BASE_SI,0,0,101325,0.0,[1.0]);
print(r)
```
yields

REFPROPdlloutput(z=array('d', [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]), Output=array('d', [-9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0]), hUnits='Q', iUCode=0, x=array('d', [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]), y=array('d', [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]), x3=array('d', [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]), q=0.0, ierr=812, herr='[REFPROP error 812] The input code Q is invalid because it is not always clear if the value is given on a mass or mole basis.  Use QMOLE or QMASS instead.')

for which the solution is to follow the instructions in herr:
```
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
root = 'd:/Program Files (x86)/REFPROP'
RP = REFPROPFunctionLibrary(root)
RP.SETPATHdll(root)
r = RP.REFPROPdll('Water','PQmole','Qmole',RP.MASS_BASE_SI,0,0,101325,0.0,[1.0]);
print(r)
```
yielding

REFPROPdlloutput(z=array('d', [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]), Output=array('d', [0.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0]), hUnits='-', iUCode=0, x=array('d', [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]), y=array('d', [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]), x3=array('d', [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]), q=0.0, ierr=0, herr='')

**Comment by EricLemmon** [comment]
Is this issue resolved?  If so, can you close it?
