### ISSUE TITLE
issue calling SETREFdll to compare with GUI data

### ISSUE THREAD

**Issue by ballachango** [usnistgov/REFPROP-wrappers#26]
Hi all,

I have been experimenting with uncommenting the line below as suggested to compare with the GUI results.
```
312 % The routine does not have to be called, but doing so will cause calculations
313 % to be the same as those produced from the graphical interface for mixtures.
314 %   [href dummy dummy dummy dummy dummy ierr2 errTxt] = calllib(libName, 'SETREFdll', href, 2, z, 0, 0, 0, 0, 0, 32*ones(255,1), 3, 255);
```
However, I always get the following error:
```
Error using calllib
Parameter can not be converted to a character vector
Error in refpropm (line 314)
```
Any hints on how I could proceed?

(As a side note, I noticed that a lot of the commented-out lines have "dummy" where the active lines have "~". Is it worth me preparing a commit for this and similar syntactical recommendations from MATLAB?)

**Comment by ianhbell** [comment]
The dummy is old-school MATLAB syntax, and should be replaced in all cases with ~.  A PR updating that would be very welcome!

________________________________

**Comment by padevel** [comment]
I found the issue with SETREFdll - the error argument had not been cast to "char".

I made two pull requests - one with just syntax updates and the fix for the above, and a second that modifies refpropm's behaviour slightly to add some flexibility.

Please consider one or the other depending on what you'd like to include.
