### ISSUE TITLE
Old Matlab Wrapper does not work

### ISSUE THREAD

**Issue by ahmadke** [usnistgov/REFPROP-wrappers#261]
Hi,

I initially followed the steps described bellow to couple Matlab R2019b with REFPROP 10 but I receive the following error (image attached). Could you please let me know to solve this issue?

Thank You,

https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/MATLAB/legacy

![REFPROP_MATLAB_ERROR](https://user-images.githubusercontent.com/61562502/75813281-8c3a1f00-5d44-11ea-99f9-c5138ed5ba0f.png)

**Comment by ianhbell** [comment]
Please first try to use the Python interface.  Solves a lot of random problems with the legacy interface that are impossible to debug.

**Comment by EricLemmon** [comment]
It's possible that you have an old Water.fld file somewhere on your machine.  Windows makes ghost directories and stores random things in there, including copies of the fluid files from previous versions.  Do a full system search for *.fld, especially in hidden and Windows system directories.  If you find anything other than in the Refprop directory, delete it!  Search for refprop.dll and refprp64.dll as well.

**Comment by EricLemmon** [comment]
Has this issue been resolved?

**Comment by ahmadke** [comment]
This issue has not been resolved yet and we paid $300 for REFPROP.

**Comment by EricLemmon** [comment]
Thanks for letting us know; I've reopened the issue so that we can try to resolve this.

Here's what I wrote back on April 3rd, can you try these steps to see if they help:

It's possible that you have an old Water.fld file somewhere on your machine. Windows makes ghost directories and stores random things in there, including copies of the fluid files from previous versions. Do a full system search for *.fld, especially in hidden and Windows system directories. If you find anything other than in the Refprop directory, delete it! Search for refprop.dll and refprp64.dll as well.

**Comment by ianhbell** [comment]
I should also reiterate that the old MATLAB wrapper is no longer supported and you should try with the new Python-based one.

**Comment by ahmadke** [comment]
This is the new python based one which does not work with Matlab.

**Comment by ianhbell** [comment]
But the link in your first posting refers to the legacy interface, so I was confused.  Can you please show the code you tried to run?

**Comment by EricLemmon** [comment]
Have you searched for an old water.fld file or old refp*.dll files on your machine yet?  This is most likely not a matlab issue, but a ghost directory issue containing old files.

**Comment by EricLemmon** [comment]
We have not heard back from you, please email us directly if you have further questions and we will work with you individually to solve them.  (eric.lemmon@nist.gov or ian.bell@nist.gov).
