### ISSUE TITLE
How to access SATGV from Excel?

### ISSUE THREAD

**Issue by MFirmin-AE** [usnistgov/REFPROP-wrappers#262]
First and foremost, thank you for supporting and enhancing REFPROP, it’s an excellent resource.

Description: This is a question rather than an issue.

Is there any way that a phase boundary calculation for a single mixture could be initiated from Excel and the resulting temperature-pressure points be brought into Excel?

After spending considerable time perusing the REFPROP documentation and github for guidance, I realize that if there is a way to do this, then it must be done with care.  
REFPROP-wrappers issues #31 & #106 come the closest to addressing my question.

If necessary, I can provide additional details on why I need to do this.

REFPROP Version: 10.0
Operating System: Windows 10 Pro Version 1709 OS Build 16299.665

Accessing REFPROP via:
REFPROP Windows GUI (REFPROP.EXE)
Excel Wrapper, i.e. REFPROP Excel Add-in (REFPROP.XLA)

**Comment by ianhbell** [comment]
If you really want to call the ``SATGVdll`` function it is possible, but I would recommend instead that you use a language like Python or C++ that interfaces more cleanly with DLL (shared libraries).

If you just want to do phase equilibrium calculations from Excel, then you should check out the documentation for how to do that.  If you can provide an example calculation you would like to do, we can explain how to do it.

**Comment by EricLemmon** [comment]
The best way to generate the entire phase diagram for a mixture is to use the saturated density as the input to the DLL.  In so doing, Refprop will automatically use the SATGV routine to calculate the outputs.  In fact, I believe that SATGV is used by all Refprop phase calculations now, and the other older routines are used only when SATGV fails.

Before you start calculations of the phase diagram, it is very important that the SATSPLN routine is called otherwise the calculations in the critical region may fail.  There is a semi-bug in the version 10 xls file where it may take a bit of trickery to get the program to call the splines (I believe you found some of that document in your links above).  If you find that things are not working, please let us know and we'll send you some updates.  Once you have that done, simply start at a low density in the vapor and then continue with a constant step size from that density to the liquid phase and you'll have a very nice set of numbers you can use to plot the phase envelope.  The step size doesn't have to be constant, but it works quite well except at low densities where a logarithmic use of input densities works much better.

**Comment by MFirmin-AE** [comment]
Thank you gentlemen,
When using the Windows GUI to calculate a phase boundary, a dialog box appears with fields to input initial density, final density and increment.  The initial density and the increment both appear to default to a value of 1, however the fluid mixture composition appears to determine the value for the final density.  
**Is this final density also known as the saturated density?**
If so, then this piece of information should help me proceed with my project.  
If you don't mind, I'd like to keep this thread open until I complete my project, in case I need additional information related to this subject.  If I'm able to finish my project without additional questions then I'll be sure close the thread.

**Comment by ianhbell** [comment]
Not exactly, but close...  What you are getting from that dialog is the isopleth of the phase envelope, often just called "the phase envelope".  The algorithm first does a phase equilibrium (dewpoint) calculation at a very low density and then goes up in density until it hits your specified maximum density.  

Things to watch out for that might differ from reality:
* The mixture may actually solidify before reaching the specified density (it is assumed that the mixture is equilibrium of liquid and vapor

You are always getting saturated density along the isopleth, because you have the saturated liquid in equilibrium with the saturated vapor.

**Comment by NickAtNight62** [comment]
I am not sure what you are asking. 

Perhaps you are looking for something like this?

Solving for Density of water for a set of temperatures.
- Both vapor and liquid phases.
- Setup for 3 fluids
-- Using a dropdown list of selecting Units
-- Using a dropdown list for selecting Property
-- Starting from Critical temperature and working down.

- Enter values in YELLOW cells only

![image](https://user-images.githubusercontent.com/58614082/78054811-3a3ae800-7348-11ea-8fda-3328970b3e6a.png)

Ditto, but switching to Thermal conductivity

![image](https://user-images.githubusercontent.com/58614082/78054551-e16b4f80-7347-11ea-958b-f04f927c5e80.png)

Source file:
[Refprop Sample.xlsx](https://github.com/usnistgov/REFPROP-wrappers/files/4410477/Refprop.Sample.xlsx)

**Comment by EricLemmon** [comment]
Has this issue been resolved and can it be closed?

**Comment by MFirmin-AE** [comment]
Not yet…I’d like to keep it active a bit longer if that’s OK.

**Comment by EricLemmon** [comment]
Can this issue be closed now?  You can always open it back up if you want.

If you need more help, let us know!

**Comment by MFirmin-AE** [comment]
Thanks to Ian, I now realize that saturated density is the density when vapor and liquid are in equilibrium.  I don't know why I was missing that because by it's very name, it should have been obvious.  **I suppose that when the vapor and liquid of a given fluid mixture are in equilibrium, at a given pressure and temperature, there are two saturated densities, one for the vapor and one for the liquid, correct?**
When I use the Windows GUI to calculate a phase boundary, an "Input Property Range" dialog box appears with fields to input initial density, final density and increment. The initial density and the increment both appear to default to a value of 1, however the fluid mixture composition appears to determine the value for the final density.  
**I still don't understand how the final density shown in Input Property Range dialog box is determined?
Is it simply the saturated liquid density at a low temperature and low pressure**
Sorry for keeping this open for so long.  It may be quite a while before I'm able to put much time into this project so thanks in advance for your response and after you responded you can go ahead and close this issue.

**Comment by EricLemmon** [comment]
The upper value in that dialog for density is probably just a mole fraction average of the triple points of the pure fluids, I don't remember how I programmed it, but since we don't know the density where the fluid goes from liquid to solid, the value doesn't have much meaning.  Here are some other issues that have lots of questions.  If they are not enough, let me know.  

I'll close this, but you can continue to add questions when they arise.

#283 
https://github.com/usnistgov/REFPROP-issues/issues/225
https://github.com/usnistgov/REFPROP-issues/issues/79
