### ISSUE TITLE
Get REFPROP information into RDBMS (SQL)

### ISSUE THREAD

**Issue by nite320** [usnistgov/REFPROP-wrappers#265]
I would like to make database with all REFPROP values in SQL and then query as needed for calculations using fluid/gas properties.

**Comment by ianhbell** [comment]
Ummm.. I don't think that will be possible.  REFPROP is not a database in the conventional sense, it is a collection of models, rather than "data".  But you could run the models for a selection of data points, and store those calculations in the database, but then you would need to interpolate within the data later on, which is not ideal.  Can you say a bit more about your use case?

**Comment by nite320** [comment]
Similar to how you would call REFPROP in MATLAB, but I would like to do it in SQL.

**Comment by ianhbell** [comment]
Sorry, I have no experience with that, but I think you need to write a C interface to call external library from SQL?  At least that's my recollection?

**Comment by nite320** [comment]
Okay thank you!
