### ISSUE TITLE
Excel Wrapper - subroutine SATGV not implemented

### ISSUE THREAD

**Issue by greedyj4ck** [usnistgov/REFPROP-wrappers#31]
Hello,

Newest excel wrapper available here, do not include declarations for **SATGVdll** subroutine. 
I can only assume that new version of wrapper will be released with premiere of RP10.  

Best regards, 
Slawomir

**Comment by ianhbell** [comment]
Hi Slawomir,  

The Excel wrapper is intentionally not exposing all the functions that are in the DLL.  It's a maintenance nightmare to do so.  If you wanted to add ``SATGVdll``, you could follow our model and add it.  But we are only going to expose the high-level functions.  If you want to do serious computation, you shouldn't be using Excel in the first place, which is why we have only a limited subset of the functionality available in Excel.
