### ISSUE TITLE
Problems using Excel to calculate quality and density

### ISSUE THREAD

**Issue by ldovalxx** [usnistgov/REFPROP-wrappers#315]
I have some problems using Excel to calculate the quality and density of vapor and liquid phases given pressure, temperature and gas composition. The spreadsheet is attached for your reference.

**Comment by EricLemmon** [comment]
There was no spreadsheet attached, can you attach it again?

**Comment by ldovalxx** [comment]
See attached.

**Comment by ldovalxx** [comment]
Hi Eric,

Please, see attached. I am having problems to attach the excel file using GitHub. Please take a look at rows 231 to 266. They are highlighted in yellow color.

Thank you,
Regards,
Luiz G. Do Val

**Comment by ldovalxx** [comment]
Please, check rows 231 to 266 of the excel spreadsheet. They are highlighted in yellow color.
Regards,
Luiz

**Comment by ianhbell** [comment]
Can you please email the spreadsheet directly to ian.bell@nist.gov and I can forward to Eric?

**Comment by EricLemmon** [comment]
Hi Luiz,

I took a look at your spreadsheet and was astounded by so many rows!  I think I got to about 7000 before my machine quit working.  Also, you are using an extremely complex mixture, which should not be a problem for Refprop if your calculations are implemented properly; but when you use Excel to do this, you become subject to Excelmania.  (I'm sure that's not a real word, but it's good for describing the craziness that happens in such spreadsheets.)  Excel will jump around randomly calculating properties, so if you are unlucky and it jumps from one mixture to another and to another (of different compositions), it could be a very long time for things to finish.  If it were smart and started at the top and did one row at a time, the speed could be quite acceptable.  

Take a look at #106 to learn how to deal with complicated mixtures.  If the spline algorithms work properly, the mixture calculations will be as fast as you see when the GUI is calculating properties.  But, that is only true if the spline routine is called only once for each composition.  If it jumps around randomly, your speed will be devastated!

If you have some programming skills, the best thing to do would be to use something like Python or the VBA code in Excel to write the routines yourself to make these calls.  The total number of lines should be less than about 50 to do all this.  The other way is to set up a separate Excel file for each mixture (of the same composition), thus forcing it to call the splines only once per a defined composition.

Eric

**Comment by ldovalxx** [comment]
Hi Eric,

Thank you very much for your feedback!!!

Here, I am attaching a spreadsheet (called Luiz) with only one line to calculate liquid and vapor phase density. If you see the command Phase shows 2-phases but the spreadsheet is still showing the same density for liquid and vapor phases. So, I am still having the same problems as before. Also, I have took a look at #106. I have run the GUI and the GUI could not perform the calculation for the same conditions presented below. I am using the alpha DLL version for excel and GUI.

Also, I would like to know which DLL version do you recommend to me to use. Should I use the ones that came with the GUI when I have bought it or Should I use the alpha or beta versions?

Kind Regards,
Luiz G. Do Val

[cid:image001.png@01D65E8A.920AD6D0]

**Comment by EricLemmon** [comment]
Hi Luiz,

I tried your point and found that it is in the retrograde area and very close to the phase boundary as you can see in the picture below.  This is perhaps one of the hardest regions for VLE root solving to converge, especially with something this complex.  Even with the splines turned on (from SATSPLN), the algorithm is not able to find the true VLE state, but rather returns something that looks like a single phase state.  

This is unfortunately something I will not be able to fix quickly and anytime soon due to the backlog of work that we have.  Most likely the values that you got back are within the uncertainty that you would find anyway when near the critical point or within the retrograde region.  But you should try different options, such as calculating saturation states given pressure, temperature, or density, to see how rapidly things change there and perhaps find a solution that would allow you to continue.

I've marked this with the "feature-request" flag to remind me to come back to this when time is available.

Eric

![image](https://user-images.githubusercontent.com/42392984/88888236-2f5f6980-d1fb-11ea-993a-7771c4b5408f.png)

**Comment by ldovalxx** [comment]
Hi Eric,

Thank you for your support! I very appreciated it. I agree with you, it is very difficult to solve VLE root very close to the phase boundary.

And no worries, I will be waiting for new news.

Kind Regards,

Luiz do Val

**Comment by EricLemmon** [comment]
OK, will do.  I'm closing it for now, but the feature-request flag will remind us to fix it and I have it stored in my list of things to fix.

**Comment by ldovalxx** [comment]
Hi Dr. Eric,

Good evening. Thank you very much.

You know, we cannot live without Refprop. After Google, Refprop is my best friend.

Have a good coming weekend,

All the best,

Luiz do Val

**Comment by EricLemmon** [comment]
Thanks for the nice words!  It brought a big smile to my face.
