### ISSUE TITLE
REFPROP 10 error 105 for Propylene

### ISSUE THREAD

**Issue by MRiva1989** [usnistgov/REFPROP-wrappers#333]
## Description

Dear all, I can't compute propylene properties on Refprop 10 using the Excel add-in (REFPROP.XLA), but not with the graphical interface (REFPROP.EXE). The error does not appear with other components. The error do not depends on the inputs  values
### Steps to Reproduce

1. On the Refprop.XLS file, I go to the "Available Properties" sheet, and I replace the default fluid name (Methane) by Propylene 
2. I observe the results on the cells containing the properties calculation (D17 to D147)

**Expected behavior:** I expect to obtain some values , different from the values obtained with preavious fluid (methane)

**Actual behavior:** I obtain this error message : #[SETUP error 105] Selected equation (TC1) not found for component #1

### Versions

**REFPROP Version:** I'm Using Refprop10 version
**Operating System and Version:** Windows 10
**Access Method:** Excel add-in on Refpop.XLS file

### Additional Information

The error only appears with propylene. 
![image](https://user-images.githubusercontent.com/72968938/96236806-c76c2400-0f9c-11eb-9627-fb5c35aadb62.png)

**Comment by ianhbell** [comment]
I tried this on my side, worked perfectly, I have tagged Eric and let's see what he says.

**Comment by EricLemmon** [comment]
You most likely have either an old propylen.fld file (note that it is spelled propylen.fld, not propylene.fld because of the old DOS 8 character naming system) or an old refprop.dll (or perhaps refprp64.dll) file on your machine.  Do a full system search including hidden and system files for "*.fld" and "refpr*.dll" to see what it finds.  If it does find something additional that is not in your refprop directory, delete it! (or perhaps rename it just in case)

**Comment by MRiva1989** [comment]
Thank you very much, the problem was an old refprop directory stored on a plugged  usb key .  thank you
