### ISSUE TITLE
SETUPdll allways returning a error for OTH / OT0

### ISSUE THREAD

**Issue by Jonshagen** [usnistgov/REFPROP-wrappers#345]
Hi,

I am connecting a tool to refprop and I am making it return the error messages.

I call SETUPdll before I call SETREFdll according to the manual. If I use OTH or OT0 I then get:

"[SETUP warning -105] Must use routine SETREF for (OTH) reference state choice; default (DEF) will be used."

My understanding is that this is not a problem since I call SETREFdll after. Is this correctly understood?

I can check if I get -105 from SETUPdll and then ignore the message, but maybe there is another solution?

Thanks

**Comment by EricLemmon** [comment]
You don't need to call SETREF at all unless you have a particular need.  However, since you are working with mixtures, I suspect you are only calling it to set the parameter to apply the reference state to the currently defined mixture (or perhaps the other way around).  In such a situation, indeed, you should just ignore this error message unless you would like it to do something different.  If so, let us know and we'll explain how to do it.

**Comment by Jonshagen** [comment]
Yes, I am only defining a reference state same for all components. Thanks for clarifying, I will skip this warning.
Thanks
