### ISSUE TITLE
Multithreading Support

### ISSUE THREAD

**Issue by ESArtman** [usnistgov/REFPROP-wrappers#355]
### Description

I am calling Refprop several thousand times in the span of a minute.  I want to leverage multithreading to decrease calculation time.  However, to my knowledge, Refprop is not thread safe.  I am running this in C# in Windows 10.  How can I use multithreading to increase speed?

### Versions

**REFPROP Version:** V10.0
**Operating System and Version:** Windows 10
**Access Method:** C# wrapper

**Comment by ianhbell** [comment]
Which C# wrapper do you use?

In general, you are correct.  REFPROP is neither thread-safe nor process-safe by default. If you can interop with C++, I made a library that allows you to have multiple copies of REFPROP loaded into memory: https://github.com/usnistgov/REFPROP-manager (windows and linux). That solves part 1 of the problem by giving each instance of the shared library its own block of memory. That doesn't solve part 2 of the problem though, because you still have different instances trying to make colliding calls to the same fluid file (they are blocking calls and REFPROP doesn't wait if it can't load the file right now). If you know that you will only have a few working fluids or sets of mixture components, then you can call ``SETFLUIDS/SETMIX/SETUP`` in _SERIAL_ to instantiate the instances, then parallel calls once they are loaded.  Alternatively, you can create an entire separate folder for each instance of the DLL with its own set of ``FLUIDS`` and ``MIXTURES`` directories, and call ``SETPATHdll`` for each instance to indicate that it should load files relative to the root of the separate folder.

Here is an example of this general approach in Python: https://github.com/usnistgov/REFPROP-wrappers/blob/master/wrappers/python/ctypes/examples/pool_example.py

And with the manager class in C++: https://github.com/usnistgov/REFPROP-manager/blob/master/test/test2.cpp

Sadly none of these tools natively support C#. But I hope this gives you some ideas.
