### ISSUE TITLE
Refprop DLL setup with Labview

### ISSUE THREAD

**Issue by Westermeyer1** [usnistgov/REFPROP-wrappers#371]
### Description

Need help setting up Refprop in Labview

### Versions

**REFPROP Version:** 10
**Operating System and Version:** Windows 10
**Access Method:** Labview Wrapper

### Additional Information

I'm trying to get enthalpy from pressure and temperature inputs. Can you let me know which DLL and VIs I need so i can get started

**Comment by ianhbell** [comment]
@dslauria can you take a stab at this one?

**Comment by damianlauria** [comment]
There are a couple of examples in the wrapper that should allow you to do this. The easiest is probably to use the  Refprop_Example_main.vi example. Using the TP code, you can select your fluid and input the temperature and pressure, and it should give you back everything, including Enthalpy (H):

![image](https://user-images.githubusercontent.com/27294065/117321836-b4db0e80-ae4a-11eb-87b6-eeccc30fca59.png)

It's also worth looking at the Refprop Tester vi and project, because that will help you to verify that you have the REFPROP dll installed and configured properly, as well as giving you examples of each of the available functions of REFPROP in isolation which might make them easier to understand.
