### ISSUE TITLE
SATSPLN Error when using 10.0097

### ISSUE THREAD

**Issue by mnotarnicola** [usnistgov/REFPROP-wrappers#378]
### Description

I'm receiving an error message when calling the SATSPLNdll function with 10.0097.

### Steps to Reproduce

Unfortunately I'm receiving this during an optimization run so I don't have the specific conditions that are yielding the error.  I'm calling the SATSPLNdll when I use a 50/50 water/glycol mixture.  Previously I had not had issues with calling this function until I started running 10.0097.  I was originally running the previous beta dll because I had an issue with the 50/50 water/glycol mixture that was resolved in case #385.

**Actual behavior:** 

Error using ctREFPROP>SATSPLNdll (line 2742)
Python Error: OSError: exception: access violation reading 0x0000000004A10000

### Versions

**REFPROP Version:** 10.0097
**Access Method:** Python wrapper through MATLAB.

**Comment by EricLemmon** [comment]
It's been about a week now since you wrote this - have you had any success locating the problem or finding a set of conditions that causes the problem?  Without this then it becomes quite difficult to isolate where the error happens.

When you say "glycol", I assume you mean ethylene glycol.  Is your 50/50 ratio on a mass or molar basis?

**Comment by mnotarnicola** [comment]
It's a 50/50 by volume mixture so I'm inputting it as 76/24 by mass.

I have not been able to recreate the issue this week so going to close it and chalk it up as an issue between chair and keyboard.

**Comment by EricLemmon** [comment]
We call it PICNIC:  Problem in chair, not in computer.

Glad to hear it's working now.
