### ISSUE TITLE
Working with REFPROP and NI DIAdem 2020

### ISSUE THREAD

**Issue by sdurand89** [usnistgov/REFPROP-wrappers#379]
Hello

We are using the REFPROP Labview wrapper in some acquisition softwares.
We are considering using NI DIAdem for the post-analysis of our results, so we tried using REFPROP in DIAdem.
However it seems that DIAdem does not support the REFPROP DLL. The NI support suggested a work around by trying to "convert" the DLL to a Labview VI and then calling this VI inside a DIAdem Script, but same thing : the DLL is not supported.

I would like to know if anyone has an idea on how to best approach this topic.

### Versions

-DLL version 9.1
-Labview version 2019 32 bits
-DIAdem version 2020 
-Windows 10 64 bits

**Comment by damianlauria** [comment]
We do not directly support the NI DIAdem package. However, the LabVIEW wrapper will allow you to use REFPROP within a LabVIEW program and any standard data file types produced by the LabVIEW program should be consumable by DIADem.

The LabVIEW wrapper is written for use with the 32-bit version of the REFPROP dll. DIAdem only comes in 64-bit versions since 2017. It is possible that the issue in DIAdem is that there is a mismatch between the 64-bit DIAdem application and the 32-bit dll. This is nothing more than an educated guess, but there is a chance that the 2017 32-bit version of DIAdem will be compatible. It should be downloadable from the NI website if you want to try that option. Alternatively, you can try the 64-bit version of REFPROP, but that will require a 64-bit version of LabVIEW, and the wrapper files will have to be updated to point to the correct version of the dll.

Here are some links that you might find helpful:
https://www.ni.com/en-us/innovations/videos/08/what-is-ni-diadem-.html
https://www.ni.com/en-us/support/documentation/supplemental/13/using-dataplugins-with-diadem.html
https://www.ni.com/en-us/support/documentation/supplemental/10/using-dataplugins-with-labview.html
https://www.ni.com/pdf/manuals/373422m.pdf
