### ISSUE TITLE
Matlab properties not matching refprop GUI properties

### ISSUE THREAD

**Issue by bsondelski** [usnistgov/REFPROP-wrappers#44]
I have been having the issue where properties extracted from REFPROP using MATLAB do not match properties extracted directly from the REFPROP GUI. These issues are occurring specifically with 10% H20 and 90% CO2 at a pressure of 18 MPa and a temperature range of 350 to 500 K, but I suspect they are occurring in mixtures with other concentrations of H2O and CO2. I've attached plots comparing the properties obtained from MATLAB vs those obtained from REFPROP. I've also attached the code used to get the properties in MATLAB. Is there any way to deal with this issue?

[Matlab code matlabVrefprop.docx](https://github.com/usnistgov/REFPROP-wrappers/files/2116948/Matlab.code.matlabVrefprop.docx)

[refprop vs matlab properties.docx](https://github.com/usnistgov/REFPROP-wrappers/files/2116889/refprop.vs.matlab.properties.docx)

**Comment by ianhbell** [comment]
Is your composition molar or mass?  I think mass, right?

The differences are likely due to the use of the splines in the GUI, and their being disabled in the legacy MATLAB wrapper.  The attached code carries out the same calculations with REFPROP 10, and demonstrates similar problems.  The mixture of CO2 + water is particularly nasty, especially because it is not a Type I mixture, and even with turning on the splines, I am not able to get the routines to succeed *all* the time.

``` python
import matplotlib.pyplot as plt

import os, numpy as np
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary

def isoline(k, ispln):
    RP = REFPROPFunctionLibrary(os.environ['RPPREFIX'])
    RP.SETPATHdll(os.environ['RPPREFIX'])
    MOLAR_BASE_SI = RP.GETENUMdll(0,"MOLAR BASE SI").iEnum
    
    x,y = [],[]
    for T in np.linspace(350, 600):
        r = RP.REFPROPdll("CO2 * WATER","PT",k,MOLAR_BASE_SI,1,ispln,18e6,T,[0.9, 0.1] + [0.0]*18)
        print(r.ierr, r.herr)
        y.append(r.Output[0])
        x.append(T)
    return x,y

if __name__=='__main__':
    os.environ['RPPREFIX'] = r'D:\Code\REFPROP-cmake\build\10\Release\\'

    for k in 'S','H','D':
        for ispln in 0,1:
            x,y = isoline(k,ispln)
            plt.plot(x,y,label=ispln)
        plt.title(k)
        plt.show()
```
S:
![s](https://user-images.githubusercontent.com/11966765/41625918-cce0829a-73d7-11e8-9edd-b0f85cfb578e.png)

H:
![h](https://user-images.githubusercontent.com/11966765/41625940-d7e0586e-73d7-11e8-9c12-ed993d392f2e.png)

D:
![d](https://user-images.githubusercontent.com/11966765/41625944-dbf25f2e-73d7-11e8-9bc3-fb1db4a96361.png)

**Comment by ianhbell** [comment]
Does that help?

**Comment by bsondelski** [comment]
I think with entropy still not matching, I will just take the data straight from the Refprop GUI for this mixture, thanks!

**Comment by ianhbell** [comment]
This is a bug in how REFPROP handles mass-based compositions in the REFPROPdll function. We are working on a patch.  In the meantime, you can workaround this problem by calling SETFLUIDSdll at the beginning, and passing an empty string to REFPROPdll for the fluid name.

**Comment by EricLemmon** [comment]
I realize this issue is now many months old, but I looked into it again to be sure it was fixed.  I tried several different options, and obtained very smooth behavior when the splines were used, but saw a bit of jumping around when not.  I also ran into the issue discussed in #74 under certain paths for making the calculations.  I am also trying this through the Fortran code, which quite possibly could taint the problem.  Below is my code, aside from the problem explained in issue 74, the output was very smooth.  For complex mixtures such as these, we will never achieve 100% convergence, but we are working towards better convergence on a regular basis.  The use of the splines is currently your best option to obtain satisfactory results when such problems occur.

```
      open (unit=2,file='d:\data.dat')
      hfld='co2;water|.9;.1 mass'
      call REFPROP2(hfld,' ',' ',1,1,p,t,z,Ou,q,ierr,herr)
      call SATSPLN(z,ierr,herr)
      p=18
      do t=350,600,1
        z(1)=.9
        z(2)=.1
        call REFPROP2(hfld,'pt','s',1,1,p,t,z,Ou,q,ierr,herr)
        write (2,*) t,ou(1)
      enddo
```
