### ISSUE TITLE
REFPROP EXCELadd-in problems

### ISSUE THREAD

**Issue by JacekZUDT** [usnistgov/REFPROP-wrappers#483]
Good morning

I'm user REFPROP ver.10
I have a problem with parameter "phase" inEXCEL add-in.
For "Typical Natural Gas", please look at the appendices, I don't understand why for the same parameters in REFPROP and EXECEL I have different information about the medium "phase". 
I change iFag in EXCEL-add-in from switch off to switch on, but in some parameters is still difference phase.
![image](https://user-images.githubusercontent.com/115729567/195652349-3f5687e5-257c-4649-9395-aa04f0a88771.png)

In EXCEL the phase is “Superheated gas” and

![EXCEL add-in](https://user-images.githubusercontent.com/115729567/195652559-a1f09050-9a2f-40eb-b631-5b39850a6543.png)

In REFPROP “Supercritical gas”
![REFPROP](https://user-images.githubusercontent.com/115729567/195652716-ef95805f-df58-4efb-9d0e-305064f4e2fd.png)

Thank you for help.

Best Regards
Jacek Żaczyński

**Comment by ianhbell** [comment]
Unfortunately the GUI and the shared library use different strings for the same quantity (in this case)

**Comment by JacekZUDT** [comment]
> 

What can i do in this situation, i would like to get the same results in EXCEL add-in, could you suggest any solution ?

**Comment by JacekZUDT** [comment]
> Unfortunately the GUI and the shared library use different strings for the same quantity (in this case)

What can i do in this situation, i would like to get the same results in EXCEL add-in, could you suggest any solution ?

**Comment by ianhbell** [comment]
I don't think there is a way, as the GUI does thing differently than the shared library.

@EricLemmon am I correct?

**Comment by JacekZUDT** [comment]
> I don't think there is a way, as the GUI does thing differently than the shared library.
> 
> @EricLemmon am I correct?

I need this information for PSV calculations, I need to know what kind of phase will be, which two results are more appropriate in GUI or in EXCEL add-in?

**Comment by ianhbell** [comment]
I don't know what PSV calculations are, but defining the phase for mixtures is challenging indeed. There is no one true answer, like there is for pure fluids.

**Comment by JacekZUDT** [comment]
> I don't know what PSV calculations are, but defining the phase for mixtures is challenging indeed. There is no one true answer, like there is for pure fluids.

Dear Ian, thank you for your explanations.
For your knowledge, I need to know what type of phase is, to choose the right formulas, different for gas phase, different for liquid and different for two-phase flow. And what about other values, e.g. critical temperature,
 critical pressure, density, the isentropic exponent, are these values in Excel add-in for mixtures correct ??
Best regards
Jacek

**Comment by EricLemmon** [comment]
If I remember right, the DLL in Version 10.0 returned a string for one of the phases that didn't make sense and we have since changed that.  Do you have the update for 10.0?  If not, Ian can provide that for you (Ian.Bell@nist.gov).  Another way to help determine the phase is through the quality.  A value less than 0 (but not less than -10) is in the liquid phase, although its actual value is not really meaningful.  A value greater than 1 is in the vapor phase.  Other regions will return numbers as explained in the documentation.

The critical parameters for mixtures should match those in the GUI if you have activated the splines.  Search for SATSPLN in this github website and you'll find all sorts of information about it.

**Comment by ianhbell** [comment]
The very notion of "gas" and "liquid" breaks down above the critical temperature/pressure. I and my co-authors have proposed a new way to think about where this line might be: https://pubs.acs.org/doi/abs/10.1021/acs.jpclett.1c01594

Eric is right though that if you are definitely subcritical, checking the vapor quality is your best bet, and fastest too since string comparisons are slow, if you care about computational speed.
