### ISSUE TITLE
Unable to Build .sln in VS 2022

### ISSUE THREAD

**Issue by gshockxcc** [usnistgov/REFPROP-wrappers#484]
### Description
I am very new to VS code, but I am trying to follow the instructions step-by-step.
I am unable to Build the .sln in VS 2022.
I installed VS Code and VS 2022.  I opened the .sln file in VS 2022, but there is no option to Build | Rebuild the PrimeREFPROPwrapper.
I also opened the .sln file in VS Code and verified the target is "x64".
If I have done something incorrectly, please advise.

### Versions
**Mathcad PRIME:** 8.0
**REFPROP Version:** Refprop 10  
**Operating System and Version:** Windows 11  
**Access Method:** Matlab & Excel, both functioning

### Additional Information

Screenshots

![image](https://user-images.githubusercontent.com/31823386/196497697-91fe0071-2bf0-4af2-aae0-09611c294724.png)

![image](https://user-images.githubusercontent.com/31823386/196497846-c358b525-4b43-494c-acdf-32392dbea528.png)

**Comment by ianhbell** [comment]
@henningjp  is the one for this question.

But *why* are you trying to build it yourself?

**Comment by gshockxcc** [comment]
My understanding is that I need to rebuild it so that it can be added to the Custom Functions folder for Mathcad. 

Is this not the correct way to call Refprop in Mathcad?

**Comment by henningjp** [comment]
@ianhbell - There's no binary DLL stored in the repo.  Do you have a place to put one?  I didn't think it wise to load it as a binary in the repo.  I can certainly put one there (it's < 200KB, but not a trackable file).

@gshockxcc  - To be clear **VS Code** is just an editor.   What you want is **Visual Studio 2022**.  You will need a license; either a paid commercial license or register a VS Community license (free for students and open-source developers).  I suspect, since **Build** is missing from your main menu, that you do not have a license yet.  A quick Google search shows that this **_may_** be because you haven't yet selected a configuration (drop-down just under Debug on the main menu).  See below.

![image](https://user-images.githubusercontent.com/17114032/196575746-cf6d581e-cd1d-4a59-abad-ecedd6dbff8e.png)


After that  is all set up, your original screenshot shows that ``RefpropPrimeWrapper`` solution is properly loaded.   Go to **View** and open the **Solution Explorer** panel (it will open on the right hand side of the VS window.  Select ``PrimeREFPROPWrapper`` at the top of the Solution Explorer tree (See figure below).

Next, make sure that the **Prime 8** configuration is selected form the dropdown (see figure below) if that is the version you have.  (Prime 7 is available, as well as Prime 6, but Prime 6 is discontinued by PTC).

![image](https://user-images.githubusercontent.com/17114032/196577621-468f8730-3f17-4ddd-9734-855b3d0adbf4.png)


**_Make sure Mathcad Prime is not running._**

Now select **Build | Build PrimeREFPROPWrapper**.  The solution will build and install the REFPROP wrapper into your Prime 8 (or Prime 7 if that's the configuration you chose) Custom Functions folder.  The REFPROP wrapper functions will be available the next time you start up Mathcad Prime.

![image](https://user-images.githubusercontent.com/17114032/196577591-98e35e66-cb1d-4432-9869-ae51a8d99350.png)

Hope that helps.

**Comment by gshockxcc** [comment]
@henningjp Thank you for the guidance.  I know it's not directly related to an issue with the wrapper, but I really appreciate the help.  

I have the "Community" version of Visual Studio.

![image](https://user-images.githubusercontent.com/31823386/196600419-7eddb8e1-68f4-4d9c-92bc-bfb724137eac.png)

![image](https://user-images.githubusercontent.com/31823386/196599899-95818e6a-9fc9-4afb-acaf-97d82ef7c791.png)

I am thinking that perhaps I don't have the correct modules or extensions installed.  Maybe?

I am not able to select the module dropdown under Debug.  That makes me think that I'm missing some component or feature.

![image](https://user-images.githubusercontent.com/31823386/196601208-0e3deaf5-c4d3-4e62-a10a-bb93140d62ce.png)

Thanks in advance for the help.

**Comment by henningjp** [comment]
Rerun your installer and make sure these components are checked for install.

![image](https://user-images.githubusercontent.com/17114032/196619500-a82c718b-3bb4-43ec-9fdc-eab514044948.png)

**Comment by henningjp** [comment]
@ianhbell - Repeat of question above.  Is there a good place to put the compiled versions of the Mathcad DLL?  A wise person once taught me not to put binaries in the git repo.  Do you (NIST SRD) have a SourceForge location maybe?  I notice that the Excel binaries right in this repo.  That would certainly allow users to avoid build their own.

**Comment by ianhbell** [comment]
It's a good question, I am not sure I have a super awesome solution, but if you send them to me, I can put them in our S3 bucket and give you the URL

**Comment by gshockxcc** [comment]
> Rerun your installer and make sure these components are checked for install.
> 
> ![image](https://user-images.githubusercontent.com/17114032/196619500-a82c718b-3bb4-43ec-9fdc-eab514044948.png)

Jeff, I'm at a loss as to what's wrong.  I have completed the updates to the modules as you suggested, and I noticed that I'm running VS Community, the same as your earlier screenshot.  I still don't have the ability to change the Configuration to select either Prime 7, or Prime 8.  When I try to open the solution file, I get this error.

![image](https://user-images.githubusercontent.com/31823386/196843545-786de0c5-3452-4b96-89e4-0f3a8be76c72.png)

I'm at a loss as to what I'm missing.

**Comment by henningjp** [comment]
I know at least one other user has downloaded the file and compiled it.

However, I develop in VS 2015 and have only eve "pushed" to GitHub.  I have opened the solution in VS 2022 and it compiles fine, but it's not one that I have pulled from GitHub.   Maybe something isn't getting pushed or pulled correctly.

I'll pull the repo down to a new directory and see what happens here.  I'll let you know.

**Comment by henningjp** [comment]
No problem there.  I cloned the repo from GitHub using:

```
$ git clone https://github.com/usnistgov/REFPROP-wrappers.git --recursive
```

The `--recursive` is important to get the externals directory.  Open the solution file from `REFPROP-wrappers\wrappers\Mathcad\buildPrime` in VS 2022.

I do get a request to convert and retarget the solution to Windows 10 SDK and upgrade to the v143 toolset.  You should answer **OK** (Yes).

![image](https://user-images.githubusercontent.com/17114032/196851496-035d3755-d825-4681-aef1-4e6ca8763cb6.png)

This happens because the wrapper is developed, built, on VS 2015 for backward compatibility, in case users have older VS versions.  Some warnings/errors come up during this process, but they can be ignored.

If you just open VS 2022 and choose "Create New Project" from the opening menu, is **Build** on the main menu?  Can you compile and run this "Hello World" program?

**Comment by gshockxcc** [comment]
> I know at least one other user has downloaded the file and compiled it.
> 
> However, I develop in VS 2015 and have only eve "pushed" to GitHub. I have opened the solution in VS 2022 and it compiles fine, but it's not one that I have pulled from GitHub. Maybe something isn't getting pushed or pulled correctly.
> 
> I'll pull the repo down to a new directory and see what happens here. I'll let you know.

I wouldn’t presume that there is anything wrong with your code.  I downloaded the files under the buildPrime folder by right-clicking and selecting Save As. I didn’t see any other way to copy the files. Should I use the command line as you did?

**Comment by gshockxcc** [comment]
> No problem there. I cloned the repo from GitHub using:
> 
> ```
> $ git clone https://github.com/usnistgov/REFPROP-wrappers.git --recursive
> ```
> 
> The `--recursive` is important to get the externals directory. Open the solution file from `REFPROP-wrappers\wrappers\Mathcad\buildPrime` in VS 2022.
> 
> I do get a request to convert and retarget the solution to Windows 10 SDK and upgrade to the v143 toolset. You should answer **OK** (Yes).
> 
> ![image](https://user-images.githubusercontent.com/17114032/196851496-035d3755-d825-4681-aef1-4e6ca8763cb6.png)
> 
> This happens because the wrapper is developed, built, on VS 2015 for backward compatibility, in case users have older VS versions. Some warnings/errors come up during this process, but they can be ignored.
> 
> If you just open VS 2022 and choose "Create New Project" from the opening menu, is **Build** on the main menu? Can you compile and run this "Hello World" program?

I was able to figure out the "Hello World" template and open the project.  The configuration settings were available,  I tried to clone the repository (just trial and error - I don't really know what I'm doing).  I was able to clone the repo, but I can't figure out how to force the --recursive.

![image](https://user-images.githubusercontent.com/31823386/196901182-4bf69320-3769-489f-aa63-c5c9ec948d6e.png)

![image](https://user-images.githubusercontent.com/31823386/196901906-1f58b4c1-0773-4c24-91d9-9c517af4f24d.png)

I can open the .sln and rebuild the RefpropWrapper ...

![image](https://user-images.githubusercontent.com/31823386/196902008-7c1a65f2-c719-45e9-9033-2c32122ae063.png)

But I get the error message below: 

![image](https://user-images.githubusercontent.com/31823386/196902305-4edba6f9-36ab-43e7-8809-b0d73c1e9e36.png)

**Comment by gshockxcc** [comment]
> $ git clone https://github.com/usnistgov/REFPROP-wrappers.git --recursive

Jeff, how are you running this command?  Is this done in the Git CLI?

**Comment by gshockxcc** [comment]
Inexperience user with GitHub.  Required installing Git and cloning repository as Jeff stated above.

**Comment by henningjp** [comment]
@gshockxcc - Sorry, I was off-line yesterday.  Sounds like you got this all figured out.

Note: you can pull down the zip file of the repository, but it does not get the full externals directory.  You have to browse to the externals repo and pull those down as well and manually uncompress them into the externals folder.

Using the git CLI with clone --recursive is by far the easiest and less error prone.
