### ISSUE TITLE
Mathcad add-in does not find REFPROP on start

### ISSUE THREAD

**Issue by mdsrjw** [usnistgov/REFPROP-wrappers#494]
FINAL EDIT 24Dec22: Looks like I took "NIST REFPROP 9.1 or later" too literally. I actually did a bit of diving into the code and discovered that it is only meant to work with V9 and NOT v10.  In light of this, I suppose my question has now become "will there be support for v10 of RefProp at any point in time?"

I have successfully compiled the PrimeREFPROPWrapper.dll using VS 2022 community edition. It places the dll in the correct Mathcad directory upon completion.  However, whenever I start Mathcad, I receive the "NIST RefProp Add-In" message dialog that says: "Add-in requires later version of REFPROP. Make sure that NIST RefProp 9.1.1 or later is installed." I clearly have the program installed in the default location (The executable is here: "C:\Program Files (x86)\REFPROP\REFPROP.EXE"). I tried a debug on the dll and I receive this message when I first step in:

![image](https://user-images.githubusercontent.com/43067316/209413357-bd698640-2f17-4c57-a473-6b66dc25b5ed.png)

I am at a loss as to where to go from here. I am pretty convinced that I had everything properly set to create an X64 output for this dll, but I am definitely not a professional programmer so there surely are things I am overlooking. Any help would be greatly appreciated. Thanks!

EDIT 24DEC22: I uncommented lines 329-333 of refprop.cpp which I will call the "debugging pop-up" which reports "The NIST RefProp DLL was found. Version: RPVersion_loaded". When I run Mathcad now, I get this pop-up:

![image](https://user-images.githubusercontent.com/43067316/209441941-bc061e0a-6dcb-4cf4-a775-f5c41de62833.png)

Since it appears to be finding the appropriate 64-bit version, this just further adds to my confusion. I also want to add that I have the user environment variable of NIST_PATH = C:\Program Files (x86)\REFPROP. Just hoping to add more info in case someone can help. Thanks again!

**Comment by henningjp** [comment]
@mdsrjw I will look into this, but it will be after the holidays.

1. I tested with version 9.1 after creating the wrapper for REFPROP 10.0 a year or so ago.

2. I’m pretty sure that **_I assumed there was nothing between versions 9.1.x and 10.0.0.0_**. This may be the cause for the error.  Version 9.9.9.0 is unexpected and must be a pre-release version of REFPROP 10.  Maybe @ianhbell  can comment on what that version is exactly.  I’ve never seen it.  If the version is < 10.0, then it must be 9.1.  I don’t think it will recognize your version, which is in the gap.  If you update to 10.0.x, it should work, but I’ll look at updating it for pre-release versions of RP10 if @ianhbell thinks this is a good idea.

3. The Legacy API functions have been tested with REFPROP 10.0 and later updates as well.

4. An update is in the works that will implement the REFPROP 10 High-Level API functions.  I have all the functions working and am just working on the docs.  Probably I’ll push this some time in January.  It has checks in it for each of the High-Level API functions that insist that the version is 10.0.0.0 or higher is found and loaded. 

Since you have the code compiling and working, you could also make the change to accept versions > 9.1 instead of exactly = 9.1.

Stay tuned.

**Comment by mdsrjw** [comment]
Thanks for your Christmas Eve reply Jeff. I did manage to get things working but had to modify the Refprop.cpp file by changing the vMajor == 9 to vMajor == 10 in line 336 of the code (see snippet below - yes, it is butt ugly, but it works). It compiled properly and I have a good indication that it is actually running in Mathcad since I return "rp_getNIST(0) = "NIST RefProp Library Version 9.9.9.0" in the program (I didn't realize at first that the new functions do not show up in the "All Functions" menu selection in Mathcad so was confused as to whether the DLL was actually functional). I am running DLL version 10.0a of Refprop. Very glad to hear that you and others have been willing to continue developing the code for v10 of Refprop.

   // Check that at least REFPROP 9.1.1 is installed before loading the DLL
            if ((vMajor < 9) || ((vMajor == 10) && (vMinor != 1) && (vPatch != 1)))
            {
                MessageBox(hwndDlg, "Add-in requires later version of REFPROP.\n\nMake sure that NIST RefProp 9.1.1 or later is installed.", "NIST RefProp Add-In", 0);
                break;
            }

**Comment by henningjp** [comment]
@ianhbell and @EricLemmon - What’s the cut off version for REFPROP 10 functions that should be coded in wrappers?  I assumed 10.0.0.0, and the the last previous release was 9.1.1, but this issue indicates that there are others in between.

**Comment by henningjp** [comment]
@ianhbell and @EricLemmon - What’s the cut off version for REFPROP 10 functions that should be coded in wrappers?  I assumed 10.0.0.0, and the the last previous release was 9.1.1, but this issue indicates that there are others in between.

**Comment by ianhbell** [comment]
I would say 10.0.0 is a good starting point.  The only serious thing to add beyond that is maybe ABFLASH.
