### ISSUE TITLE
TQFLSH error 2 and #VALUE! error in Excel

### ISSUE THREAD

**Issue by PhilippJR** [usnistgov/REFPROP-wrappers#496]
I copied the RefProp Excel VBA module to an already existing add-in. I now have access to `=Refprop()`, but sometimes the calculations do not work.

Example 1:
I entered `=REFPROP("T";"R407C";"EOSMIN")` in several cells, saved, closed and opened the file. This is the result:
![image](https://user-images.githubusercontent.com/81237852/211999063-bc722d93-f282-47d6-a6af-f13139a82252.png)
When I enter and leave the cell, the calculation works, but often not on the first attempt.

Example 2:
Sometimes I get a `#VALUE!` error ("`#WERT!`" in German):
![image](https://user-images.githubusercontent.com/81237852/212000524-5c051d73-0909-467f-9bfc-d8f40746b0ec.png)
Please note, that the formula is slightly different. There is an additional `-273.15`. When I now
- enter and leave the cell, the calculation works, but again often not on the first attempt
- remove the `-273.15`, I get the TQFLSH error from the first screenshot. Again, entering and leaving the cell, delivers the correct value, but often not on the first attempt.

**REFPROP Version:** 10.0  
**Operating System and Version:** Windows 11
**Access Method:** Excel 365, 64bit

**Comment by ianhbell** [comment]
@EricLemmon you are the Excel guru, any idea?

**Comment by ianhbell** [comment]
My unhelpful answer would be to use a procedural programming language that does things in order for easier debugging of issues like this (but it is true!), but that doesn't help solve your problem. Hopefully @EricLemmon will have some idea.

**Comment by NickAtNight62** [comment]
EOSMin would be a lookup value?

i can duplicate your results.

Occasionally the result is an error because … oh, he says.    Calc density is 18.6439 mole/L and max density is 18.5724 mole/L

As a calc error, seems like the problem should exist in Refprop also.

**Comment by PhilippJR** [comment]
Thanks for your answers.
It is getting even worse. Please find attached an example file.
When I open it, I get many `#VALUE!` errors:
![image](https://user-images.githubusercontent.com/81237852/212244581-d4cdbbf8-c847-49a2-a5b8-ab731aec61bd.png)

I have to enter and leave cell B3 exactly three times to obtain the correct values. It must be cell B3, probably, because everything depends on this cell.
Now, I get many TPFLSH error 2:
![image](https://user-images.githubusercontent.com/81237852/212245070-cfe354f1-7a0e-4a31-854b-45f2d89dc053.png)
I can obtain the correct values again by entering and leaving every single cell exactly three times but there are really many TPFLSH errors...
I could do so, but a workbook change that forces a recalculation, e.g. deleting a row or open the workbook, leads to the `#VALUE!` errors and after entering and leaving cell B3 all TPFLSH errors are back.

[RefProp TPFLSH error 2.xlsx](https://github.com/usnistgov/REFPROP-wrappers/files/10408520/RefProp.TPFLSH.error.2.xlsx)

**Comment by NickAtNight62** [comment]
“> I cannot calculate the value in the RefProp GUI:”

You are getting the same ‘warning message’.  See the ‘Error Status’ in that window.

TPFLSH is the Fortran subroutine that was called.  When your request causes a calculation error, it gives you the specific problem.  In this case, that it calculated a liquid density above the maximum allowed density. 

In red prop, you have to press ‘yes’ to proceed with the calculation.

so that makes sense as to why Excel needs the extra ‘return’ to move from the ‘error message’ to the value.

**Comment by NickAtNight62** [comment]
If in Refprop I request T,P, Rho, Q and specify a temp of 500 K and a quality of 1

I get a TQFLSH error 121 saying that my input temp of 500 K is above the maxcondentherm temperature of 359.343K

**Comment by NickAtNight62** [comment]
Hmm, a double error !

Decreasing from 200K to 140 K in 20 K increments, with Q of 0 (or liquid)

works for 200,180,160, gives a double error at 140.

Triple point or min temperature is 152.392K

And calculated Density of 19.0959 is above the limit of 18.5724 mol/L

selecting ‘yes’ on the error returns no result.

![5EBB6AEF-9E23-467E-B044-732188D14A1D](https://user-images.githubusercontent.com/58614082/212403987-c76d3d11-4518-44d6-879c-6b60174a7e6b.jpeg)

**Comment by NickAtNight62** [comment]
So using smaller steps shows the e limit is reached at 154.4 K.  The density slowly approaches the limit.

We should be able to reach the triple point of 152.392 K.  

So perhaps the error is that the calculated maximum liquid density is just a touch too low?  

![image](https://user-images.githubusercontent.com/58614082/212405118-7a9f9ac6-54a7-4bfe-b29b-a2c48a2ce5fa.jpg)

**Comment by NickAtNight62** [comment]
> Now, I get many TPFLSH error 2:

Those errors are easy enough to get rid of... 

If you look at what your spreadsheet is doing, it is generating the error whenever the temperature gets below 154.4 K !  

Put an If statement in and tell Excel to NOT CALCULATE this formula when the Temperature falls below the minimum temperature of 154.4 K. 

![MinTemp](https://user-images.githubusercontent.com/58614082/212414428-3c881339-6d27-4cf3-b07a-75efab1410be.png)

**Comment by PhilippJR** [comment]
I just printed what the RefProp macro passes to and gets from the REFPRP64.DLL for the three times, I have to enter and leave the cell. In the following "before" and "after" mean "before/after `Call REFPROPdll(...)`"
![image](https://user-images.githubusercontent.com/81237852/212679981-0bb1d8aa-fc03-460f-bdb3-e7f2bf0e8d19.png)
On the first try, no refrigerant is passed in. Anyway, there is a result: Output(1)=152,39... That does not make sense to me. However, the result is overridden with the error message.
On the second try the refrigerant is passed in, the output is exactly the same but is also overridden.
On the third try everything is exactly the same as on the second try, but no error is produced and therefore, I get the result. This does not make sense, because the REFPRP64.DLL should deliver the same result, when the inputs are the same.

**Comment by NickAtNight62** [comment]
> On the first try, no refrigerant is passed in. Anyway, there is a result: Output(1)=152,39...

Interesting.  That (152.39 K) is the Triple point for R407C.  So that is the answer.  Don't know why you are getting that result with no fluid sent.  Perhaps clear the pallete - calculate EOSMIN for a different fluid, then see what the Output is for a 'no fluid' pass.  Either the 152.39 K is a default value in the fortran program, or the program is remembering the last fluid run.

**Comment by NickAtNight62** [comment]
> Now run the following macro:

Now that is a Novel solution.  That works, but I don't think that would be a good practice. You are automatically generating the Yes that the Fortran program needs to progress beyond the warning error. 

But the fortran warning error exists for a reason. I don't think it is prudent to bypass the error.

**Comment by NickAtNight62** [comment]
> The first quote states that the values can be calculated, the second assumes that it is not possible.

No, the second solution avoids the problem.

You will need Eric Lemmon to fix the underlying fortran code.  That is where the error lies.  See the above post that calculates density (kmol/m3) as the temperature decreases for a liquid.  

The fortran TQFLSH ( Temperature, Quality, Flash) is generating a maximum density of 18.5724 mole/L.  It should be generating a maximum density higher than that. That error then stops the TQFLSH program early (154.4 K versus the expected triple point of 152.39 K)

Eric could also modify the Excel program to better handle the results when TQFLSH generates a warning message. But I think I prefer the current setup. We should get the warning error when the fortran casts an error.  (1) to stop the program from continuing on and giving a dubious result.  (2) to put the warning into the notes for the cell, and automatically continue on (don't think many people read the notes, so perhaps would also need to flag the results with a red color/italics to indicate an error).

**Comment by PhilippJR** [comment]
> Either the 152.39 K is a default value in the fortran program, or the program is remembering the last fluid run.

I made a copy of the file, changed the fluid to R407**B** and calculated everything. Then I went back to the original file with R407**C**. Although no fluid is passed to the RefProp.dll, I get the triple point of R407**C**. This is strange but I will not investigate this further.

> That works, but I don't think that would be a good practice.

Agreed. I will accept that there is a min temperature. I did not accept this before, because I thought, when the values can be calculated, why not on the first try. I think, this should be fixed in the Excel macro. It should not be possible to get values, that can not be obtained in the RefProp GUI for a good reason.

Thanks again Nick for your time.

**Comment by NickAtNight62** [comment]
> Thanks again Nick for your time.

You are most welcome. We need @EricLemmon's help to fix the fortran routine.

For TQFLSH (Temperature, Quality Flash in Refprop) with T=172.39 K (Triple Point) and Q=0 (Liquid) we get the FORTRAN error TQFLSH error 2 fixed.
![image](https://user-images.githubusercontent.com/58614082/212927835-1aae9ac2-76e9-4149-b763-4a90002fa3ff.png)

We can press "YES" to proceed to a result. Doing so, however, returns NO value.
![image](https://user-images.githubusercontent.com/58614082/212928329-22a6c17d-89d3-4702-bd35-501a1e8c3704.png)

So we are definitely getting a default value from the program, which just happens to be the Triple point of R407C. We are not getting a result, just the appearance of a result.

The liquid density is linear with temperature in this range (Refprop results). So the program needs a molar liquid density limit of ~18.65 kmol/m3 to stop getting the error.

![image](https://user-images.githubusercontent.com/58614082/212931117-760ca747-8b97-424b-87c7-d00f5810a73e.png)

**Comment by henningjp** [comment]
Actually, the blank hFld string behavior makes perfect sense.  By design, REFPROPdll will use the current, previously loaded, fluid if an **_empty fluid string_** is passed in and ignore hFld if the **_same fluid string_** is passed in, since it doesn't need to be replaced.  Remember that as long as Excel is open and using the REFPRP64.dll file, the DLL is open, resident (you can check the task manager), and holding onto its global state (like the last fluid file loaded).  It does this for speed since you don't want REFPROP loading the same fluid file from disk over and over and over again off the disk.  As long as your worksheet is using the same fluid/mixture for all its calls, you get the optimum performance.

However, can cause issues in non-procedural codes like Excel and other high-level processors like Mathematica and Mathcad.  If you evaluate a different fluid (type in a new formula) somewhere else on the sheet (or even on a **_different sheet_** or in a **_different workbook_** that is also open) re-evaluation of that calculation with a blank hFld string should give you the new (last loaded) fluid.  It will depend on the order in which the cells are evaluate.  When relying on this behavior, it is always a good idea to re-evaluate the entire worksheet/workbook so that cells are calculated in order (downward).

For grins, shut excel down completely, open a blank workbook and call REFPROP with a blank/empty hFld string.  You should get an error that no fluid is loaded.   Load and actual fluid/mixture anywhere else on the sheet and your evaluation with the empty hFld string will now evaluate because a fluid has been loaded by the DLL.

**Comment by PhilippJR** [comment]
> For grins, shut excel down completely, open a blank workbook and call REFPROP with a blank/empty hFld string. You should get an error that no fluid is loaded. Load and actual fluid/mixture anywhere else on the sheet and your evaluation with the empty hFld string will now evaluate because a fluid has been loaded by the DLL.

I can reproduce this behavior. Very interesting.
And your performance explanation makes perfect sense. Thanks.

**Comment by henningjp** [comment]
### The other problem is due to a mismatch in the mixture properties at the triple point:

From the REFPROP DLL Documentation for REFPROPdll under EOSMIN:

- EOSMIN: Return the property specified in hOut at the minimum temperature allowed in the equation of
state. This is generally at the triple point in the liquid phase.

The temperature at EOSMIN is therefore the Triple point liquid temperature for the mixture, which is returned as 152.392.  This is a weighted average of the Triple Point Temperature for the pure fluid components.  The density at this point is taken from the end of the Liquid Saturation Spline Curve (built with a call to SATSPLN, which is done internally in the Excel and REFPROP GUI) and results in  18.664 mol/L.

**Dmax**, per the REFPROP DLL Documentation, for LIMITSdll states

-  for mixtures, a simple mole fraction weighting [of the pure components] in reduced variables is used.

With an independent mass weighted reduced variable calculation of Dmax for each component (retrieved from REFPROP using hout = "DMAX(1)", "DMAX(2)", and "DMAX(3)", I cannot get exactly the value that REFPROP returns, 18.5724 mol/L, but it is close and still less than the saturation value at the triple point that the spline curve returns.

While these two methods to get the density at EOSMIN return values that are very close, the saturation curve value is greater than Dmax and so the error gets thrown.  I suspect that REFPROP consumes this error and simply returns a warning flag, which is why the error message is returned and then cleared on subsequent calls where values are returned.

Interestingly, I used the Mathcad wrapper to to verify the values above and it behaves exactly the same way, throwing an error message on the first calculation and then returning values on subsequent recalculations.  This is the only odd behavior that I see; that Excel, REFPROP.exe and Mathcad all throw errors and then return the calculated values anyway once the error is cleared.  

The Excel file is doing nothing more than calling REFPROPdll with various predefined flags.  You can get the full documentation for this function at [REFPROP DLL Documentation - High-Level API](https://refprop-docs.readthedocs.io/en/latest/DLL/high_level.html).
