### ISSUE TITLE
Mixture properties 

### ISSUE THREAD

**Issue by mtaktnk** [usnistgov/REFPROP-wrappers#522]
I'm user REFPROP ver.10 and calculate the mixture properties with Excel add-in. 
I have a problem with calculating "Temperature" from "Pressure and Enthalpy" in Mixture of para-hydrogen and methane.
Under the mixture rate 40%mass of para-hydrogen, calculated value of Excel add-in is different from Refprop software.
However, calculated temperature of 0%mass of para-hydrogen ( = 100% methane) with Excel add-in is the same as Refpro software.
I have no idea to avoid this issue at once, so want to know correct way to calculate the properties or alternative method. 

### Versions

**REFPROP Version:10.0
**Operating System and Version:Windows 10  
**Access Method:Excel [How you are accessing REFPROP (i.e. Python, other wrapper)]  

### Additional Information
![1](https://user-images.githubusercontent.com/127706723/224595705-67235122-b907-44e9-8743-eb9300de528e.jpg)
![2](https://user-images.githubusercontent.com/127706723/224595719-a1cfa077-4255-4396-afb0-44bd83f6a669.jpg)
![3](https://user-images.githubusercontent.com/127706723/224595741-b6126b48-31d4-41b2-a06e-3e6d56ee831e.jpg)

**Comment by NickAtNight62** [comment]
When I setup that mixture in RefProp I get a warning message:
  117: Binary interaction parameters are not presently available for this mixture; alternative mixing rules from a similiar substance have been used.

**Comment by NickAtNight62** [comment]
In Refprop: under View mixing parameters, it is using:
Mixing rule KW7 Kunz and Wanger model for the methane-hydrogen mixture
BetaT 1.0
gammaT 1.3526
Fij 1.0
BetaV 1.0
GammaV 1.0187

**Comment by NickAtNight62** [comment]
Lets see, so what is going on...
1. The pure-properties results are the same (0% Parahydrogen or 100% parahydrogen) in both Refprop and Excel
2. I can duplicate your results, but for 40% Parahydrogen, I get the error '#[PHFLSH error 248] Single-phase iteration did not converge for P = 0.4 MPA and H = 8480.88 J/mol.  
3. The issue is probably in the mixing rules that are being applied.
4. We can test this by running the case of 0.01 Parahydrogen.  That gives a temp of 584 K.  Compare to 0% parahydrogen temp of 405K.  
5. So we get a correct result with pure methane, but when a small amount of parahydrogen is added, we get erroneous results.
6. I forget how to check what mixing rules are being applied in Excel.

**Comment by nist-aharvey** [comment]
@NickAtNight62 I expect that your apparent discontinuity between pure methane and 0.01 para-H2 is because by default REFPROP uses a different reference state for mixtures than for a pure component.  If you go into Options, Reference State, and check the box "Apply Reference State to Each pure component" you should get continuity with the pure-component endpoints.

The original problem is probably a matter of REFPROP having difficulty converging sometimes when components of a mixture have very different volatility. I think @ianhbell may have suggestions for improving that.
I believe there are also some issues with use of mass fractions in REFPROP 10.0 -- it is always a good idea to try the calculation with mole fraction as the composition variable (which is that natural variable for thermodynamics and what REFPROP uses internally) to see if that fixes the problem.

**Comment by NickAtNight62** [comment]
I expanded your review a bit more. There are 4 regions:

1. From 100% to 42% Parahydrogen, the results are close. Error fits polynomial:  error=0.0022x^2-0.407+14.979.  R2=0.9806 (orange line). Results get progressively worse as we lower the parahydrogen.

2. From 41% to 34% Parahydrogen, we get an error in Excel. That plots as a 'zero' value on my excel plot. Please ignore. 

3. From 33% to 0.01% Parahydrogen, the results start off bad and get attrocious ! Error =-0.0266x^2+3.3392x-181.03 R^2=0.999. (blue line)
    CAUTION: THIS PLOT USES THE SECOND Y AXIS ON THE RIGHT. THAT WAS SO I COULD SHOW BOTH PLOTS ON ONE CHART.
    
4. From 0.05 to 0% Parahydrogen.  Only two points, so didn't bother to trend the results.

![Error Plot](https://user-images.githubusercontent.com/58614082/224823610-a0e742fa-fbb9-4b3e-bd48-9069cf684afa.png)

**Comment by NickAtNight62** [comment]
[RefProp MethanParahydrogen March2023.xlsx](https://github.com/usnistgov/REFPROP-wrappers/files/10961667/RefProp.MethanParahydrogen.March2023.xlsx)

**Comment by NickAtNight62** [comment]
[Methane Parahydrogen March 2023.txt](https://github.com/usnistgov/REFPROP-wrappers/files/10961675/Methane.Parahydrogen.March.2023.txt)

**Comment by NickAtNight62** [comment]
Note: System does not support a *.rfp file.  Could not upload that.

**Comment by ianhbell** [comment]
You can rename the .rfp file to .txt

**Comment by mtaktnk** [comment]
Thank you for replying my issue.
Following the comments, I also calculated the properties with mole fraction as the composition variable, but the results was not good (please look at the attached chart).
Even though calculating error disappear, difference between Excel add-in and Refprop is huge under 80% mole fraction of para-hydrogen.
As NickAtNight62 showed above, temperature calculated from pressure and enthalpy in Refprop approach to quadratic function. So I will calculate temperature with approximate functions and interpolation of them, at present.
![5](https://user-images.githubusercontent.com/127706723/225213644-b2876af5-bda1-4b66-be97-f90d44284254.jpg)
![4](https://user-images.githubusercontent.com/127706723/225213660-ec49cc2b-b8ab-46ac-aaf9-7a31e1796cab.jpg)

**Comment by mtaktnk** [comment]
And also I tried to calculate temperature from specific pressure and density, and compare the results from Excel add-in and Refprop. In this case, the temperature value from each methods shows good agreement. (with some errors in Excel add-in)

In NickAtNight62' comment,
_Followed by:
Enthalpy/entropy reference state calculation failed to converge for the specified mixture. reference values set for each pure component will be used instead._

I understood that calculation of mixture properties with enthalpy/entropy in Excel add-in is difficult and should be avoided.

![6](https://user-images.githubusercontent.com/127706723/225217771-9a980521-a828-428b-875c-2d3454298fab.jpg)
![7](https://user-images.githubusercontent.com/127706723/225217788-78736937-4b63-4afa-8992-0b42f9d64677.jpg)

**Comment by ianhbell** [comment]
In this case, the "similar fluid" mixing rule is used, which if you open the parahydrogen fluid file you see a line like:
```
8d757b40  (hydrogen)                      !Alternative fluid for mixing rules   :AltID:
```
which says that when you need the interactions for pH2 + methane, just use the ones for eH2 + methane

**Comment by NickAtNight62** [comment]
Ah, so it is using the Methane/Hydrogen parameters in the HMX.BNC file?

> ?Methane/Hydrogen                                          [C1/H2]
?Kunz and Wagner (2007)
  8ae7a700/8d757b40
    KW7      1.             1.352643115    1.             1.018702573    1.             0.             0. 0. 0. 0. 0. 0.
    TC5     66.626615     445.38361     -381.30154        0.             0.             0.             0. 0. 0. 0. 0. 0.
    VC5     -0.369107       0.59576944    -0.23854726     0.             0.             0.             0. 0. 0. 0. 0. 0.
    TRN     -0.28           0.207          0.99           0.98           0.             0.             0. 0. 0. 0. 0. 0.
    PR1      0.0156         0.             0.             0.             0.             0.             0. 0. 0. 0. 0. 0.

So that is the first setup warning:
[SETUP warning -117] Binary interaction parameters are not presently available for this mixture; alternative mixing rules from a similar substance have been used.

The next warning was for Natural gas mixtures.  Saying the 2008 GERG model was being used.

The first line, (KW7) is the BetaT, GammaT, Fij, BetaV and GammaV values respectively that refprop shows.

"Literature reference for Methane/Hydrogen
Kunz and Wagner (2007)
Kunz, O., Klimeck, R., Wagner, W., Jaeschke, M. The GERG-2004 Wide-Range Equation of State for Natural Gases and Other Mixtures. GERG Technical Monograph 15. Fortschr.-Ber. VDI, VDI-Verlag, Duesseldorf, 2007.Kunz, O. and Wagner, W. The GERG-2008 Wide-Range Equation of State for Natural Gases and Other Mixtures: An Expansion of GERG-2004. J. Chem. Eng. Data, 57(11):3032-3091, 2012.Methane-Hydrogen"

**Comment by NickAtNight62** [comment]
Correct parameters are applied from the paper (see page 3077 of Ref)
![Meth-H2](https://user-images.githubusercontent.com/58614082/226725343-4c6c0ba9-a2e6-4655-a977-295b987973f5.png)

Which get fed into Equations 16 and 17. (page 3041 of Ref)

![Eq16](https://user-images.githubusercontent.com/58614082/226725329-6d69d66d-8ddd-456a-99b7-ddc0e3bde40d.png)

**Comment by NickAtNight62** [comment]
Yes, that is the function.  In the help it is a Legacy API. Here is the HELP information.

> <HTML xmlns="http://www.w3.org/1999/xhtml"><HEAD>          <TITLE>Legacy API</TITLE>     <LINK href="../_static/bizstyle.css" rel="stylesheet" type="text/css">     <LINK href="../_static/pygments.css" rel="stylesheet" type="text/css">     <LINK title="Index" href="../genindex.html" rel="index">     <LINK title="High-Level API" href="high_level.html" rel="prev">     <LINK href="../_static/style.css" rel="stylesheet" type="text/css">   </HEAD><BODY><DIV class="document"><DIV class="documentwrapper"><DIV class="body" role="main"><DIV class="section" id="legacy-api"><DIV class="section" id="function-documentation"><DL class="subroutine"><DT id="f/_/GETKTVdll"><EM class="property">subroutine  </EM><CODE class="descname"><FONT color="#ffffff" style="background-color: rgb(0, 120, 215);">GETKTVdll</FONT></CODE><SPAN class="sig-paren">(</SPAN><EM>icomp</EM>, <EM>jcomp</EM>, <EM>hmodij</EM>, <EM>fij</EM>, <EM>hFmix</EM>, <EM>hfij</EM>, <EM>hbinp</EM>, <EM>hmxrul</EM>, <EM>hmodij_length</EM>, <EM>hFmix_length</EM>, <EM>hfij_length</EM>, <EM>hbinp_length</EM>, <EM>hmxrul_length</EM><SPAN class="sig-paren">)</SPAN></DT><DD><P>Retrieve mixture model and parameters for a specified binary mixture. This subroutine should not be called until after SETUP has been called. The order of icomp and jcomp do not matter, the routine returns the parameters as stored in the HMX.BNC file.  To determine if the compositions are backwards, call HMXORDER.  If calling SETMIX with the same parameters, an error will be returned if the components are backwards.</P><TABLE class="docutils" border="1"><COLGROUP><COL width="44%"><COL width="56%"></COLGROUP><TBODY valign="top"><TR class="row-odd"><TD>Kunz-Wagner model (KW0)</TD><TD>Lemmon-Jacobsen model (LJ6)</TD></TR><TR class="row-even"><TD>fij(1) = betaT</TD><TD>fij(1) = zeta</TD></TR><TR class="row-odd"><TD>fij(2) = gammaT</TD><TD>fij(2) = xi</TD></TR><TR class="row-even"><TD>fij(3) = betaV</TD><TD>fij(3) = Fij</TD></TR><TR class="row-odd"><TD>fij(4) = gammaV</TD><TD>fij(4) = beta</TD></TR><TR class="row-even"><TD>fij(5) = Fij</TD><TD>fij(5) = gamma</TD></TR><TR class="row-odd"><TD>fij(6) = ‘not used’</TD><TD>fij(6) = ‘not used’</TD></TR></TBODY></TABLE><TABLE class="docutils field-list" rules="none" frame="void"><COLGROUP><COL class="field-name"><COL class="field-body"><TBODY valign="top"><TR class="field-odd field"><TH class="field-name">Parameters:</TH><TD class="field-body"><UL class="first last simple"><LI><STRONG>icomp</STRONG><EM> [</EM><EM>int</EM><EM>,</EM><EM>in</EM><EM>]</EM> :: Component i</LI><LI><STRONG>jcomp</STRONG><EM> [</EM><EM>int</EM><EM>,</EM><EM>in</EM><EM>]</EM> :: Component j</LI><LI><STRONG>hmodij</STRONG><EM> [</EM><EM>char</EM><EM>,</EM><EM>out</EM><EM>]</EM> :: Mixing rule for the binary pair i,j (e.g., KW0, LJ6, XR0, or LIN) (character*3)</LI><LI><STRONG>fij</STRONG> (6)<EM> [</EM><EM>double</EM><EM>,</EM><EM>out</EM><EM>]</EM> :: Binary mixture parameters (array of dimension nmxpar; currently nmxpar is set to 6); the parameters will vary depending on hmodij;</LI><LI><STRONG>hFmix</STRONG><EM> [</EM><EM>char</EM><EM>,</EM><EM>out</EM><EM>]</EM> :: File name (character*255) containing parameters for the binary mixture model</LI><LI><STRONG>hfij</STRONG><EM> [</EM><EM>char</EM><EM>,</EM><EM>out</EM><EM>]</EM> :: Description of the binary mixture parameters (character*8 array of dimension nmxpar) The parameters will vary depending on hmodij.</LI><LI><STRONG>hbinp</STRONG><EM> [</EM><EM>char</EM><EM>,</EM><EM>out</EM><EM>]</EM> :: Documentation for the binary parameters (character*255)</LI><LI><STRONG>hmxrul</STRONG><EM> [</EM><EM>char</EM><EM>,</EM><EM>out</EM><EM>]</EM> :: Description of the mixing rule (character*255)</LI><LI><STRONG>hmodij_length</STRONG><EM> [</EM><EM>int</EM><EM>]</EM> :: length of variable <CODE class="docutils literal notranslate"><SPAN class="pre">hmodij</SPAN></CODE> (default: 3)</LI><LI><STRONG>hFmix_length</STRONG><EM> [</EM><EM>int</EM><EM>]</EM> :: length of variable <CODE class="docutils literal notranslate"><SPAN class="pre">hFmix</SPAN></CODE> (default: 255)</LI><LI><STRONG>hfij_length</STRONG><EM> [</EM><EM>int</EM><EM>]</EM> :: length of variable <CODE class="docutils literal notranslate"><SPAN class="pre">hfij</SPAN></CODE> (default: 255)</LI><LI><STRONG>hbinp_length</STRONG><EM> [</EM><EM>int</EM><EM>]</EM> :: length of variable <CODE class="docutils literal notranslate"><SPAN class="pre">hbinp</SPAN></CODE> (default: 255)</LI><LI><STRONG>hmxrul_length</STRONG><EM> [</EM><EM>int</EM><EM>]</EM> :: length of variable <CODE class="docutils literal notranslate"><SPAN class="pre">hmxrul</SPAN></CODE> (default: 255)</LI></UL></TD></TR></TBODY></TABLE></DD></DL></DIV></DIV></DIV></DIV></DIV></BODY></HTML>

**Comment by ianhbell** [comment]
Something like this?:
```python
import os
os.environ['RPPREFIX'] = os.getenv('HOME')+'/REFPROP10'

import numpy as np
root = os.getenv('RPPREFIX')
import ctREFPROP.ctREFPROP as ct
RP = ct.REFPROPFunctionLibrary(root)
RP.SETPATHdll(root)

z = [0.9206,0.0714,0.0078,0,0,0.0002]
znorm = np.array(z)/sum(z)
ierr = RP.SETFLUIDSdll('METHANE;ETHANE;PROPANE;BUTANE;PENTANE;NITROGEN')
print(ierr)
print(RP.GETKTVdll(1,2))
```
yielding
```
0
GETKTVdlloutput(hmodij='KW1', fij=array('d', [0.996336508, 1.049707697, 0.997547866, 1.006617867, 1.0, 0.0]), hFmix='HMX.BNC', hfij='BetaT   GammaT  BetaV   GammaV   Fij   not used', hbinp='Methane/Ethane\r\nKunz and Wagner (2007)', hmxrul='KW1  Kunz and Wagner model for the methane-ethane mixture')
```

**Comment by ianhbell** [comment]
There is the ``FIJMIX`` output in the ``REFPROPdll`` function, but it doesn't give the string information I think.

**Comment by NickAtNight62** [comment]
> Something like this?:

Yes, exactly like that.  Wow.  That is easy to do in Python.

The Excel/Visual Basic is still a bit of a mystery on how to do it.  (Probably very similar to the call in the GUI - since that is/was in Basic.

**Comment by NickAtNight62** [comment]
@ianhbell Well, I might have fat fingered it, but I got inconsistent results in the GUI interface!?!

Using the mixture, for pure Methane, I got a temp of 403.65 C for Ethalpy 2000 kJ/kg and Pressure 400 kPa.

Using pure methane, for same conditions, I got 405.5 C.

The Parahydrogen also gave different results.  -132.75 C for the mixture.  -129.49 C for pure parahydrogen.
![WhereIsTheError](https://user-images.githubusercontent.com/58614082/227799565-c43c3164-ed18-4589-a0d2-9fbbf5afacbd.png)

**Comment by ianhbell** [comment]
What do you mean by inconsistent? You need to be ensuring that you set the same reference states in each case.

**Comment by nist-aharvey** [comment]
Yes, this last problem is almost certainly a matter of reference states. Remember that the absolute value of enthalpy is meaningless (you can only talk about enthalpy change between two states) so setting the zero of the reference state is arbitrary and REFFPROP by default does something different for mixtures than it does for pure components.
You can get consistency of reference states between pure and mixture calculations in the GUI by choosing Options, Reference State, and Apply Reference State to "Each pure component".

**Comment by NickAtNight62** [comment]
> Something like this?:

Still not able to get the was not able to get the GETKTVdll function to work.  However, I modified the Sample code from above (Sample.Bas) and got that to run, Code shown below. Spreadsheet attached.  
- the unmodified Sample.bas is in Module1
- the modified version, specfic to the above problem is in Module2.

This code calls Refprop from the Visual Basic app. It then returns the results to the spreadsheet.

The result was a bit of a surprise.  See Plot 1 and 2 below.

**The surprise:  The VBA results matched the Refprop results !**

The results from the Forumula entered into the spreadsheet still differs from both Refprop GUI and the VBA generated results.
 
Changing the spreadsheet formula from Mass to Mole composition also did not help. 

I narrowed down where the problem starts/stops.
- It starts at 0.000075 mass fraction Parahydrogen in Methane. (0.0006 mole fraction)
- There is a VERY sharp temperature break in the results, where an error of 194.73, 223.16, & 273.28 K suddenly appears.

We cannot say when the error disappears exactly, there are two transitions.  The first is to the flash error result.  This occurs at:
- 0.33507 mass fraction Parahydrogen in Methane (0.8004 mole fraction)
- ALL three conditions start/end at the same compositions. That may indicate that the coding error is in the Composition section of the software for the Excel spreadsheet..

The second transition occurs at:
- 0.417476 mass fraction Parahydrogen in Methane (0.8508 mole fraction).
- We now switch from flash errors to results that are reasonably close to the other results (GUI Refprop, VBA in Excel)
- As in the first two transitions, all three conditions transition at the same time.

Perhaps the VBA version is using a different reference property than the Excel version.  The instructions to change reference state for the Excel spreadsheet are attached. perhaps a different reference condition was used in the Sample.bas from the default spreadsheet.

![Refprop Image 1](https://user-images.githubusercontent.com/58614082/229601655-d8de8a91-f94f-4646-a270-7c1e596673fd.png)

![Refprop Image 2](https://user-images.githubusercontent.com/58614082/229601676-0d6420a6-43cc-4c01-b795-a97461ec1fd9.png)



`'Attribute VB_Name = "Module1"
DefDbl A-H, O-Z
DefLng I-N
Const ncmax = 20   'Maximum number of components in the mixture (do not change unless the Refprop Fortran code is also changed with the same number in the CONSTS.INC file)
Const iPropMax = 200 'Number of output properties available in ALLPROPS (also do not change).

Private Declare Sub REFPROPdll Lib "REFPROP.DLL" (ByVal hFld As String, ByVal hIn As String, ByVal hOut As String, iUnitNumb As Long, iMass As Long, iFlag As Long, a As Double, b As Double, zm As Double, Output As Double, ByVal hUnits As String, iUnits As Long, x As Double, y As Double, x3 As Double, q As Double, ierr As Long, ByVal herr As String, ln1 As Long, ln2 As Long, ln3 As Long, ln4 As Long, ln5 As Long)

Sub Example2()

'     Nicks Version
'     Example program that uses the routines in REFPROP.
'
'     Refprop uses a default set of units, these being:
'       K, kPa, mol/dm^3, mole fraction, J/mol, J/mol-K, m/s, uPa-s, W/m-K, and N/m
'
      Dim hFld As String, hIn As String, hOut As String, hUnits As String, herr As String
      Dim Output(iPropMax) As Double, z(ncmax) As Double, x(ncmax) As Double, y(ncmax) As Double, x3(ncmax) As Double
      Dim ymass(ncmax) As Double, ymole(ncmax) As Double
      o = 1000#


'***New methods for obtaining properties from the REFPROP and ALLPROPS subroutines***  (see notes at top of file)

'...Get the DLL number of the REFPROP DLL.
      Call REFPROP(" ", " ", "DLL#", 0, 0, 0, 0, 0, z, Output, hUnits, q, ierr, herr)

'...When Refprop was installed, an environmental variable called RPPrefix was setup so that Refprop can find
'   the fluid files.  To manually set the path to these files, use the following lines.
'     Call REFPROPdll ("c:\Program Files (x86)\Refprop","Path"," ",
'    &       0,0,0,0d0,0d0,z,Output,hUnits,iUnit,x,y,x3,q,ierr,herr)
'     if (ierr>0) then msgbox herr

'...Calculate the Temperature at a given Enthalpy and Temperature with the REFPROP1 subroutine
      'Call SETFLUIDS("methane;ethane", ierr)
      'If (ierr > 0) Then MsgBox herr
      z(1) = 1#
      z(2) = 0
      iMass = 1 'Mass fractions for composition
      iU = 3  'Flag to use SI units with C
      'iU = 2  'Flag to use SI units with K
      'iU = 1  'Flag to use SI units
      H = 2000  'kJ/kg
      P = 0.4 'MPaa
      

' For Enthalpy (H) and Pressure (P) of 2000, 1500 adn 1000 kJ/kg  and 400,300,200 kPaa respectively
' For parahydrogen/methane compsitions from 100% to 0%
Dim Number As Integer
Dim Offset As Integer
Offset = 3

For Number = 0 To 100 Step 1

'For number As Double = 100 to 0 Step -1

   z(1) = 1 - (Number / 100)
   z(2) = (Number / 100)
   
      Call REFPROP("parahydrogen;methane", "HP", "T,D", iU, iMass, 0, H, P, z, Output, hUnits, q, ierr, herr) 'Temperature in K
      T = Output(1)
      D = Output(2)
      If (ierr > 0) Then MsgBox herr
      
' Call SETUPdll(ncomp, hFiles, hFmix, hrf, ierr, herr, hFiles_length, hFmix_length, hrf_length, herr_length)
' Call GETKTVdll(" ", " ", "DLL#", 0, 0, 0, 0, 0, z, Output, hUnits, q, ierr, herr)
' Call GETKTVdll(icomp, jcomp, hmodij, fij, hFmix, hfij, hbinp, hmxrul, hmodij_length, hFmix_length, hfij_length, hbinp_length, hmxrul_length)
 
'Results
      Range("A" & Number + Offset).Value = z(1)
      Range("B" & Number + Offset).Value = z(2)
      Range("C" & Number + Offset).Value = H
      Range("D" & Number + Offset).Value = P
      Range("E" & Number + Offset).Value = T
            
Next
            
'Next set
      H = 1500  'kJ/kg
      P = 0.3 'MPaa

For Number = 0 To 100 Step 1

'For number As Double = 100 to 0 Step -1

   z(1) = 1 - (Number / 100)
   z(2) = (Number / 100)
   
      Call REFPROP("parahydrogen;methane", "HP", "T,D", iU, iMass, 0, H, P, z, Output, hUnits, q, ierr, herr) 'Temperature in K
      T = Output(1)
      D = Output(2)
      If (ierr > 0) Then MsgBox herr
      
'Results
      Range("H" & Number + Offset).Value = z(1)
      Range("I" & Number + Offset).Value = z(2)
      Range("J" & Number + Offset).Value = H
      Range("K" & Number + Offset).Value = P
      Range("L" & Number + Offset).Value = T
Next

            
'Next set
      H = 1000  'kJ/kg
      P = 0.2 'MPaa

For Number = 0 To 100 Step 1

'For number As Double = 100 to 0 Step -1

   z(1) = 1 - (Number / 100)
   z(2) = (Number / 100)
   
      Call REFPROP("parahydrogen;methane", "HP", "T,D", iU, iMass, 0, H, P, z, Output, hUnits, q, ierr, herr) 'Temperature in K
      T = Output(1)
      D = Output(2)
      If (ierr > 0) Then MsgBox herr
      
'Results
      Range("O" & Number + Offset).Value = z(1)
      Range("P" & Number + Offset).Value = z(2)
      Range("Q" & Number + Offset).Value = H
      Range("R" & Number + Offset).Value = P
      Range("S" & Number + Offset).Value = T
Next


      End


End Sub

Sub REFPROP(hFld As String, hIn As String, hOut As String, iUnits As Long, iMass As Long, iFlag As Long, a As Double, b As Double, z() As Double, Output() As Double, hUnits As String, q As Double, ierr As Long, herr As String)
Dim hFld2 As String * 10000, hIn2 As String * 255, hOut2 As String * 255, hUnits2 As String * 255, herr2 As String * 255
Dim iUnits2 As Long, iMass2 As Long, iFlag2 As Long, iUCode2 As Long, ierr2 As Long
Dim a2 As Double, b2 As Double, z2(ncmax) As Double, x(ncmax) As Double, y(ncmax) As Double, x3(ncmax) As Double, q2 As Double, Output2(iPropMax) As Double

  hFld2 = hFld: hIn2 = hIn: hOut2 = hOut
  iUnits2 = iUnits: iMass2 = iMass: iFlag2 = iFlag
  a2 = a: b2 = b
  For i = 1 To ncmax: z2(i) = z(i): Next
  Call REFPROPdll(hFld2, hIn2, hOut2, iUnits2, iMass2, iFlag2, a2, b2, z2(1), Output2(1), hUnits2, iUCode2, x(1), y(1), x3(1), q2, ierr2, herr2, 10000&, 255&, 255&, 255&, 255&)
  For i = 1 To iPropMax: Output(i) = Output2(i): Next
  hUnits = hUnits2
  iUCode = iUCode2
  hUnits = hUnits2
  q = q2
  ierr = ierr2
  herr = herr2
  If Trim(hFld2) <> "" Then
    For i = 1 To ncmax: z(i) = z2(i): Next
  End If

End Sub`

**Refprop Help on reference states:**
> Reference State

Reference State

When large differences in enthalpy and entropy occur between REFPROP and tables of properties given in handbooks, please note:

The absolute values of enthalpy, entropy, and energy at a single state point are meaningless. It is only the difference between two different state points that matter. Thus, the value for a single state point can be set to any arbitrary value. Many handbooks set the arbitrary state point so that the values of these properties are positive for most liquid or gas states. You can change the values of the arbitrary state points by going to the Options/Reference State menu. Your choice of options can be permanently saved in the graphical interface by selecting Options/Save Options, and then saving the options under the file name ‘defaults.prf’.

To change the default in the Excel file, press Alt-F11 to bring up the VB code. If the code does not appear, make sure the project explorer is visible (View/Project Explorer), then click on modules, and then on module1. Then search for the call to SETREF, and change the second input from 2& to 1&. More information on this can be found in your REFPROPFortran directory in the file SETUP.FOR under the SETREF subroutine.

The reference states for enthalpy and entropy are entered in the Reference dialog. There are three common choices for the reference state on which the values of enthalpy and entropy are based. These three common choices are:
1.Setting enthalpy and entropy to zero for the saturated liquid at the normal boiling point (designated as NBP).
2.Setting enthalpy and entropy to zero for the saturated liquid at -40 °C (designated as ASHRAE).
3.Setting enthalpy to 200 kJ/kg and entropy to 1.0 kJ/(kg-K) for the saturated liquid at 0 °C (designated as IIR).

In addition, the reference state can be set manually by specifying values of the enthalpy (h) and entropy (s) at arbitrary values of temperature (T) and pressure (P).

When working with mixtures, the default setting can be used for each pure fluid, or the reference state values of enthalpy and entropy can be specified at the currently defined composition.

The exergy reference state and definition can be selected based on the user’s preference.

The reference state choices are saved with other [Preferences](mk:@MSITStore:C:\Program%20Files%20(x86)\REFPROP\REFPROP.CHM::/GUI/Menu%20Commands/Options%20Menu/preferences.html#preferences) when the [Save Current Options](mk:@MSITStore:C:\Program%20Files%20(x86)\REFPROP\REFPROP.CHM::/GUI/Menu%20Commands/Options%20Menu/savecurrentoptions.html#savecurrentoptions) command is selected. It is restored to a previously saved option with the [Retrieve Options](mk:@MSITStore:C:\Program%20Files%20(x86)\REFPROP\REFPROP.CHM::/GUI/Menu%20Commands/Options%20Menu/retrieveoptions.html#retrieveoptions) command or [Open](mk:@MSITStore:C:\Program%20Files%20(x86)\REFPROP\REFPROP.CHM::/GUI/Menu%20Commands/File%20Menu/opensession.html#opensession) command.

[RefpropIssue Rev1.xlsx](https://github.com/usnistgov/REFPROP-wrappers/files/11141507/RefpropIssue.Rev1.xlsx)
