### ISSUE TITLE
Two-phase regime: liquid and vapor properties

### ISSUE THREAD

**Issue by schonx** [usnistgov/REFPROP-wrappers#550]
### Description

I have not been able to find anything on this / figure it out myself. If it is implemented, please hint me back to the documentation which I read but will happily and thoroughly read again.

In the REFPROP GUI you can chose to not only display bulk properties, but also liquid and vapor properties ( Options > Properties > Check the respective button on the lower left corner ). I am aware that, e.g. for CV, bulk properties are not defined in the two-phase regime for many properties. However, I am interested in the properties of the individual phases while being in the two-phase regime.

How would I access these values?

![image](https://github.com/usnistgov/REFPROP-wrappers/assets/82873777/cfc0c3e7-cbea-420f-9543-60e2037ece65)

The values are not identical to the corresponding saturated values at the corresponding pressure (I assume: because of the special two-phase equillibrium), so I can not get them by providing PQ with Q=1.

### Versions

**REFPROP Version:** 10.0
**Operating System and Version:** Windows 10
**Access Method:** Python Wrapper

**Comment by schonx** [comment]
Thank you kindly for your reply, Mr. Bell. I assume you are referring to this line in the description of hOut:

> *LIQ: (where * is T, P, D, etc.) Return the liquid saturation properties for the property listed as the first letter. This is only valid for saturation states or 2-phase states.

What put me off was the term "saturation" properties. Because, as mentioned above, I observed that the values are not identical to the values I would get on the saturation line. How should I understand the liquid/vapor properties of the phases in the two-phase regime? How do they relate to the properties at the saturated states for the corresponding isobares?

**Comment by nist-aharvey** [comment]
I don't understand what you are saying about saturation properties.
By definition, the properties of the vapor and the liquid when you are in the 2-phase region must be exactly the saturated liquid and vapor values.
If you are seeing (slightly?) different numbers, I might speculate that you are using a rounded value for the pressure that you put into the saturation calculation. For example, in the case you posted the real pressure might be 1.01325 bars when the GUI only shows the digits 1.0132.

If you are getting different saturation values from the single-phase properties you see in the two-phase state, please post an example showing the difference.

**Comment by schonx** [comment]
Maybe my understanding is wrong. Can you confirm that the saturated liquid and vapor values are not the ones that I would get by requesting Q=0 and Q=1 for the corresponding pressure? I am comparing the liquid and vapor values of the two-phase state to the saturated values on the phase border, which I read by requesting values for p and Q=0/Q=1. These points on the saturation line have different values than the liquid and vapor values of the two-phase state. See this example with a mixture of several hydrocarbons:


![image](https://github.com/usnistgov/REFPROP-wrappers/assets/82873777/21eeee68-adb2-4f56-98f2-6bedd1ff58d8)

**Comment by nist-aharvey** [comment]
Ah, if you are talking about MIXTURES that is a different story.
I had assumed you were dealing with pure components, since your original example looks like it was for pure water. For a pure component, the things I said still apply.

But for a mixture, you have an additional degree of freedom, which is the composition.  Q=0 and Q=1 will give you the saturation conditions (bubble and dew points, respectively) specific to that composition.  But if you have that bulk composition and put it in the 2-phase region, you will get different equilibrium vapor and liquid compositions.  Those will still be "saturation" conditions, but for their specific compositions.  In other words, if you do Q=0 with the liquid composition (NOT the bulk composition), you should get the properties of the liquid in the 2-phae region.  Similarly, if you do Q=1 with the vapor composition (again, not the bulk composition) you should get the properties of the vapor in the 2-phase region.

I am not familiar with the Python wrapper so I don't know the best way to get this calculation.  From the link Ian supplied, it looks to me like if you do a flash in a 2-phase state you can get back LIQ and VAP values that would correspond to the phases in the 2-phase state -- you could of course test that by comparing results with the GUI (I strongly suggest doing any testing with a simple 2-component mixture to make matters simpler).  A more roundabout way would be to do it in multiple steps, doing the 2-phase flash first and then doing Q=0 and Q=1 calculations with the resulting equilibrium liquid and vapor compositions.  But I think it is likely you can get it all in one shot based on the documentation Ian (who is on travel this week so may not be able to help for a while) pointed you to.

**Comment by schonx** [comment]
Thank you so much for clarifying Mr. Harvey! Your in-depth explanation and Mr. Bell's hint to the documentation solve my issue indeed. Again, big thanks to both of you for your time. I will close this issue.
