### ISSUE TITLE
Bug in Python Wrapper

### ISSUE THREAD

**Issue by igor144** [usnistgov/REFPROP-wrappers#84]
### Description
The following program:
``` python
import os, numpy as np
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary

def NBP():
    RP = REFPROPFunctionLibrary(os.environ['RPPREFIX'])
    RP.SETPATHdll(os.environ['RPPREFIX'])
    SI = RP.GETENUMdll(0,"SI").iEnum
    
    r = RP.REFPROPdll("HELIUM","TSAT","Dliq",SI, 0,0, 4.4, 0, [1.0])
    print(r.ierr, r.herr, r.Output[0], r.hUnits, r.iUCode)
   
if __name__=='__main__':
    # If the RPPREFIX environment variable is not already set by your installer (e.g., on windows), 
    # then uncomment this line and set the absolute path to the location of your install of 
    # REFPROP
    # os.environ['RPPREFIX'] = r'D:\Code\REFPROP-cmake\build\10\Release\\'
    
    # Print the version of REFPROP in use and the NBP
    NBP()
```
gives uncorrect output:

```
(0, u'', 120.91281592176075, u'-', 0)
```

**Expected behavior:** It should give units for density.

**Actual behavior:**  It gives '-' instead of kg/m^3

### Versions

**REFPROP Version:** 10.0a 
**Operating System and Version:** Windows 10
**Access Method:** Python Wrapper

**Comment by ianhbell** [comment]
Thanks for the report, this is a bug in REFPROP.

**Comment by igor144** [comment]
Dear Jan,

I found another bug
```python
import os, numpy as np
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary

def NBP():
    RP = REFPROPFunctionLibrary(os.environ['RPPREFIX'])
    RP.SETPATHdll(os.environ['RPPREFIX'])
    SI = RP.GETENUMdll(0,"SI").iEnum
    ierr = RP.SETFLUIDSdll("HELIUM")
    z,c,q,ierr,herr = RP.REFPROP1dll("TSAT","P",SI, 1, 4.4, 0, [1.0])
    print(z,c,q,ierr,herr)

if __name__=='__main__':
    # If the RPPREFIX environment variable is not already set by your installer (e.g., on windows), 
    # then uncomment this line and set the absolute path to the location of your install of 
    # REFPROP
    # os.environ['RPPREFIX'] = r'D:\Code\REFPROP-cmake\build\10\Release\\'
    
    # Print the version of REFPROP in use and the NBP
    NBP()
```
The output is
```
(array('d', [1.0]), 0.11907583031460638, 0.0, 0, u'MPa')
```
Please, note at **u'MPa'**.

Jan, is it possible to get the correct version of **REFPROP**?

**Comment by igor144** [comment]
Jan,
Unfortunately new DLL's, you have sent me, have the same problem with units for Dliq and Dvap.

**Comment by ianhbell** [comment]
Indeed, I don't have the capability to fix them right now.

**Comment by igor144** [comment]
I see.

**Comment by EricLemmon** [comment]
What was originally thought to be a simple error turned out to be quite complex (which is why this is 11 days old now) because of the possible impact to other output in the Refprop subroutine, requiring careful debugging to ensure that the final change was the correct one.  I believe that this is true of the code I just changed, but it will require much beta testing to see if any new problems appear.  

We are keeping two sets of code since Refprop 10 was released, one is the official patch that contains only a few minor updates to address several important bugs that have appeared, and the other is the beta version of what will eventually become version 10.1.  The bug fixed here falls under the latter category since we have kept the official patch limited to only those updates that we know will not affect other parts of the program.

If you would like the new beta release, please contact us (eric.lemmon@nist.gov or ian.bell@nist.gov).
